import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const ethicalHackingMethodologySkill = defineSkill({
  id: "ethical-hacking-methodology",
  fullName: "授权渗透测试方法论",
  description: "当用户需要在合法授权范围内做 Nmap 侦察、Linux 提权、AD 攻击、路径遍历、认证绕过、deeplink 滥用、API Fuzzing 或常见 Web 漏洞渗透测试时使用。",
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "active-directory-attacks",
      source: new URL("./references/active-directory-attacks.md", import.meta.url),
      target: "references/active-directory-attacks.md",
      title: "active-directory-attacks.md",
      summary: "Reference material for ethical-hacking-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "api-fuzzing-bug-bounty",
      source: new URL("./references/api-fuzzing-bug-bounty.md", import.meta.url),
      target: "references/api-fuzzing-bug-bounty.md",
      title: "api-fuzzing-bug-bounty.md",
      summary: "Reference material for ethical-hacking-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "broken-authentication",
      source: new URL("./references/broken-authentication.md", import.meta.url),
      target: "references/broken-authentication.md",
      title: "broken-authentication.md",
      summary: "Reference material for ethical-hacking-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "file-path-traversal",
      source: new URL("./references/file-path-traversal.md", import.meta.url),
      target: "references/file-path-traversal.md",
      title: "file-path-traversal.md",
      summary: "Reference material for ethical-hacking-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "intent-deeplink-abuse",
      source: new URL("./references/intent-deeplink-abuse.md", import.meta.url),
      target: "references/intent-deeplink-abuse.md",
      title: "intent-deeplink-abuse.md",
      summary: "Reference material for ethical-hacking-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "linux-privilege-escalation",
      source: new URL("./references/linux-privilege-escalation.md", import.meta.url),
      target: "references/linux-privilege-escalation.md",
      title: "linux-privilege-escalation.md",
      summary: "Reference material for ethical-hacking-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "nmap",
      source: new URL("./references/nmap.md", import.meta.url),
      target: "references/nmap.md",
      title: "nmap.md",
      summary: "Reference material for ethical-hacking-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "top-web-vulnerabilities",
      source: new URL("./references/top-web-vulnerabilities.md", import.meta.url),
      target: "references/top-web-vulnerabilities.md",
      title: "top-web-vulnerabilities.md",
      summary: "Reference material for ethical-hacking-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "evals",
      source: new URL("./evals/", import.meta.url),
      target: "references/evals",
      title: "Eval Cases",
      summary: "Eval cases for ethical-hacking-methodology.",
      loadWhen: "Read only when validating or improving this skill.",
    })
  ],
});
