import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const pptGenerateSkill = defineSkill({
  id: "ppt-generate",
  fullName: "PPT 端到端生成",
  description: "当用户要从零生成演示文稿、从文档/主题生成 PPT、或要求 AI 端到端制作幻灯片时使用。",
  useCases: [
    "用户给出主题/需求，要求生成完整演示文稿。",
    "用户提供源文档（PDF/文本/URL），要求转化为 PPT。",
    "用户说\"帮我做个 PPT\"、\"生成幻灯片\"、\"做个 deck\"。",
    "用户要求先看多套真实页面预览、图像级视觉方向或 image-first 成稿，再确认整套 PPT。",
    "区别：[ppt-visual](references/ppt-visual.md) 只输出设计说明；[pptx](references/pptx.md) 处理已有文件。",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "anti-patterns",
      source: new URL("./references/anti-patterns.md", import.meta.url),
      target: "references/anti-patterns.md",
      title: "anti-patterns.md",
      summary: "Reference material for ppt-generate.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "page-types",
      source: new URL("./references/page-types.md", import.meta.url),
      target: "references/page-types.md",
      title: "page-types.md",
      summary: "Reference material for ppt-generate.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "ppt-visual",
      source: new URL("./references/ppt-visual.md", import.meta.url),
      target: "references/ppt-visual.md",
      title: "ppt-visual.md",
      summary: "Reference material for ppt-generate.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "pptx",
      source: new URL("./references/pptx.md", import.meta.url),
      target: "references/pptx.md",
      title: "pptx.md",
      summary: "Reference material for ppt-generate.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "spec-lock-template",
      source: new URL("./references/spec-lock-template.md", import.meta.url),
      target: "references/spec-lock-template.md",
      title: "spec-lock-template.md",
      summary: "Reference material for ppt-generate.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
