import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineAntiPattern,
  defineSkill,
  defineSkillGoal,
  defineSkillOutputs,
  defineSkillWorkflow,
} from "../../sdk";

export const pptGenerateSkill = defineSkill({
  id: "ppt-generate",
  fullName: "PPT 端到端生成",
  description: "当用户要从零生成演示文稿、从文档/主题生成 PPT、或要求 AI 端到端制作幻灯片时使用。",
  useCases: [
    "用户给出主题/需求，要求生成完整演示文稿。",
    "用户提供源文档（PDF/文本/URL），要求转化为 PPT。",
    "用户说\"帮我做个 PPT\"、\"生成幻灯片\"、\"做个 deck\"。",
    "用户要求先看多套真实页面预览、图像级视觉方向或 image-first 成稿，再确认整套 PPT。",
    "需要区分从零生成、只做视觉说明、处理已有 PPTX 或 image-first 成稿。",
  ],
  constraints: [
    "每页只传达一个核心观点（4±1 信息块上限）",
    "SVG 禁用 `<mask>`/`<style>`/`<foreignObject>`/`<filter>`/CSS class，只用内联属性",
    "逐页生成，不批量（防质量下降）",
    "每页生成前必须重读 spec_lock（防上下文漂移）",
    "page_rhythm 大纲阶段锁定，执行时不改",
    "image-first 只在用户明确要求视觉预览、图像级成稿或视觉保真优先时启用；普通 PPT 默认走可编辑 SVG 分支",
    "4 个 HARD STOP 必须用户确认才继续",
    "预览图必须是 16:9 的内容型页面，不用文字 mockup、空壳占位或纯装饰图冒充",
  ],
  checklist: [
    "baseline judgment 已完成并通过需求确认",
    "薄材料已生成 content_basis.md，且标注 claim status",
    "spec_lock 已锁定",
    "image-first 请求已先给真实 16:9 预览并完成风格确认",
    "已确认走可编辑 SVG 分支还是 image-first 页面图分支",
    "大纲标注了 page_rhythm 且不超过 3 页连续 dense",
    "SVG 分支每页生成前重读 spec_lock，且通过 quality checker",
    "image-first 分支没有添加未批准的后期覆盖层",
    "PPTX 可正常打开",
    "页数与 spec_lock 一致",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "跳过 hard stop：未确认需求、视觉策略、生成分支或初稿评审就继续生成。",
      pass: "四个 hard stop 都拿到确认后再推进下一阶段。",
    }),
    defineAntiPattern({
      fail: "把文字 mockup、空壳占位或纯装饰图当 16:9 预览。",
      pass: "预览必须是真实内容型页面，能暴露信息密度、视觉方向和可读性。",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  sourceDir: new URL("./", import.meta.url),
  goal: defineSkillGoal({
    body: "从主题、文档或需求端到端生成 PPT，先确认需求和视觉策略，再按可编辑 SVG 或 image-first 分支逐页生成、评审和返修。",
  }),
  workflow: defineSkillWorkflow({
    steps: [
      "阶段 1 轻量需求确认并 hard stop：用途、受众、页数/时长、材料状态、身份锚点和交付偏好。",
      "阶段 1.5 生成内容基底：薄材料先写 content_basis.md，完整材料只抽取结构，并标注 user_provided、inferred、needs_confirmation。",
      "阶段 2 锁定视觉策略和大纲并 hard stop：必要时先给 16:9 首页、目录页、正文页真实预览，再产出 design_spec、spec_lock 和 outline。",
      "阶段 3 确认生成分支并 hard stop：默认可编辑 SVG 到 DrawingML PPTX；用户明确 image-first 或视觉保真优先才走整页图像。",
      "阶段 4 逐页生成与转换：每页前重读 spec_lock；SVG 分支校验内联属性，image-first 分支默认零后期覆盖。",
      "阶段 5 初稿评审并 hard stop；阶段 6 按页返修，区分 SVG 修改、整页重生、局部编辑或内容蓝图变更。",
    ],
  }),
  outputs: defineSkillOutputs({
    items: [
      "baseline judgment、content_basis、design_spec、spec_lock、outline 和 page_rhythm。",
      "生成分支说明、逐页 SVG 或 image-first 页面图、PPTX 文件和质量校验结果。",
      "初稿评审、返修清单、页面节奏检查、可编辑性/视觉保真的取舍说明。",
    ],
  }),
  tools: [],
  references: [
    defineReference({
      id: "anti-patterns",
      source: new URL("./references/anti-patterns.md", import.meta.url),
      target: "references/anti-patterns.md",
      title: "anti-patterns.md",
      summary: "PPT 生成过程中的常见反模式及正确做法。",
      loadWhen: "PPT 生成过程中需要避免常见错误或检查生成质量时读取。",
    }),
    defineReference({
      id: "page-types",
      source: new URL("./references/page-types.md", import.meta.url),
      target: "references/page-types.md",
      title: "page-types.md",
      summary: "PPT 页面类型参考，说明不同页面布局和节奏的适用场景。",
      loadWhen: "需要确定 PPT 页面类型、布局或节奏安排时读取。",
    }),
    defineReference({
      id: "ppt-visual",
      source: new URL("./references/ppt-visual.md", import.meta.url),
      target: "references/ppt-visual.md",
      title: "ppt-visual.md",
      summary: "PPT 视觉设计说明，仅输出设计规范而不生成实际幻灯片。",
      loadWhen: "用户只需要 PPT 视觉设计说明而不需要生成实际文件时读取。",
    }),
    defineReference({
      id: "pptx",
      source: new URL("./references/pptx.md", import.meta.url),
      target: "references/pptx.md",
      title: "pptx.md",
      summary: "PPTX 文件处理参考，说明如何操作已有的 PowerPoint 文件。",
      loadWhen: "需要处理已有的 PPTX 文件而非从零生成时读取。",
    }),
    defineReference({
      id: "spec-lock-template",
      source: new URL("./references/spec-lock-template.md", import.meta.url),
      target: "references/spec-lock-template.md",
      title: "spec-lock-template.md",
      summary: "PPT 规格锁定模板，用于记录页面结构、内容与节奏的最终决策。",
      loadWhen: "需要锁定 PPT 规格、防止上下文漂移时读取。",
    }),
  ],
});
