import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const pptGenerateSkill = defineSkill({
  id: "ppt-generate",
  fullName: "PPT 端到端生成",
  description: "当用户要从零生成演示文稿、从文档/主题生成 PPT、或要求 AI 端到端制作幻灯片时使用。",
  useCases: [
    "用户给出主题/需求，要求生成完整演示文稿。",
    "用户提供源文档（PDF/文本/URL），要求转化为 PPT。",
    "用户说\"帮我做个 PPT\"、\"生成幻灯片\"、\"做个 deck\"。",
    "用户要求先看多套真实页面预览、图像级视觉方向或 image-first 成稿，再确认整套 PPT。",
    "区别：[ppt-visual](references/ppt-visual.md) 只输出设计说明；[pptx](references/pptx.md) 处理已有文件。",
  ],
  constraints: [
    "每页只传达一个核心观点（4±1 信息块上限）",
    "SVG 禁用 `<mask>`/`<style>`/`<foreignObject>`/`<filter>`/CSS class，只用内联属性",
    "逐页生成，不批量（防质量下降）",
    "每页生成前必须重读 spec_lock（防上下文漂移）",
    "page_rhythm 大纲阶段锁定，执行时不改",
    "image-first 只在用户明确要求视觉预览、图像级成稿或视觉保真优先时启用；普通 PPT 默认走可编辑 SVG 分支",
    "4 个 HARD STOP 必须用户确认才继续",
    "预览图必须是 16:9 的内容型页面，不用文字 mockup、空壳占位或纯装饰图冒充",
  ],
  checklist: [
    "[ ] baseline judgment 已完成并通过需求确认",
    "[ ] 薄材料已生成 content_basis.md，且标注 claim status",
    "[ ] spec_lock 已锁定",
    "[ ] image-first 请求已先给真实 16:9 预览并完成风格确认",
    "[ ] 已确认走可编辑 SVG 分支还是 image-first 页面图分支",
    "[ ] 大纲标注了 page_rhythm 且不超过 3 页连续 dense",
    "[ ] SVG 分支每页生成前重读 spec_lock，且通过 quality checker",
    "[ ] image-first 分支没有添加未批准的后期覆盖层",
    "[ ] PPTX 可正常打开",
    "[ ] 页数与 spec_lock 一致",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "anti-patterns",
      source: new URL("./references/anti-patterns.md", import.meta.url),
      target: "references/anti-patterns.md",
      title: "anti-patterns.md",
      summary: "Reference material for ppt-generate.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "page-types",
      source: new URL("./references/page-types.md", import.meta.url),
      target: "references/page-types.md",
      title: "page-types.md",
      summary: "Reference material for ppt-generate.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "ppt-visual",
      source: new URL("./references/ppt-visual.md", import.meta.url),
      target: "references/ppt-visual.md",
      title: "ppt-visual.md",
      summary: "Reference material for ppt-generate.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "pptx",
      source: new URL("./references/pptx.md", import.meta.url),
      target: "references/pptx.md",
      title: "pptx.md",
      summary: "Reference material for ppt-generate.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "spec-lock-template",
      source: new URL("./references/spec-lock-template.md", import.meta.url),
      target: "references/spec-lock-template.md",
      title: "spec-lock-template.md",
      summary: "Reference material for ppt-generate.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
