import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const agentOrchestrationSkill = defineSkill({
  id: "agent-orchestration",
  fullName: "Agent Orchestration",
  description: "当用户要设计多 Agent 编排、system prompt 架构、状态管理或 Agent 扩展点时使用。",
  useCases: [
    "设计多 Agent 系统：子 Agent 职责划分、fork vs fresh 决策、隔离策略。",
    "构建 system prompt 架构：静态/动态分离、缓存边界、模块化段函数。",
    "设计 Agent 状态管理：四种状态生命周期、层级配置、记忆提取。",
    "规划 Agent 扩展点：协议（MCP）、事件（Hooks）、声明式（Skills）。",
    "需要与 [agent-tool-design](references/agent-tool-design.md) 联动做工具加载策略。",
  ],
  constraints: [
    "**铁律：Fork vs Fresh 必须显式决策**——子 Agent 继承父上下文（fork）还是独立启动（fresh）不能隐含，必须按风险和隔离需求明确选择。",
    "System prompt 必须有缓存边界：静态段在前（可缓存），动态段在后，两者不能混排。",
    "每个 Agent 必须有 `max_turns` 限制，防止无限循环。",
    "状态按生命周期分四层（turn/session/persistent/project），禁止混用。",
    "扩展通过协议和事件，不通过继承或核心代码修改。",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "agent-permission-safety",
      source: new URL("./references/agent-permission-safety.md", import.meta.url),
      target: "references/agent-permission-safety.md",
      title: "agent-permission-safety.md",
      summary: "Reference material for agent-orchestration.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "agent-tool-design",
      source: new URL("./references/agent-tool-design.md", import.meta.url),
      target: "references/agent-tool-design.md",
      title: "agent-tool-design.md",
      summary: "Reference material for agent-orchestration.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "multi-agent",
      source: new URL("./references/multi-agent.md", import.meta.url),
      target: "references/multi-agent.md",
      title: "multi-agent.md",
      summary: "Reference material for agent-orchestration.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "state-extensibility",
      source: new URL("./references/state-extensibility.md", import.meta.url),
      target: "references/state-extensibility.md",
      title: "state-extensibility.md",
      summary: "Reference material for agent-orchestration.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "system-prompt",
      source: new URL("./references/system-prompt.md", import.meta.url),
      target: "references/system-prompt.md",
      title: "system-prompt.md",
      summary: "Reference material for agent-orchestration.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
