import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineAntiPattern,
  defineSkill,
} from "../../sdk";

export const iosSimulatorSkillSkill = defineSkill({
  id: "ios-simulator-skill",
  fullName: "iOS 模拟器自动化",
  description: "当用户需要用 Simulator、xcrun simctl、设备启动、截图、安装包、日志采集或提审前自动化回归时使用。",
  useCases: [
    "需要在模拟器里构建、运行、排查 iOS 应用问题。",
    "需要通过无障碍树导航界面，而不是靠像素坐标硬点。",
    "需要抓日志、截图、UI 树、权限状态、状态栏和推送来复现问题。",
    "需要批量启动、关闭、擦除、创建或选择模拟器。",
  ],
  constraints: [
    "仅把 `scripts/` 目录下的可执行 Node 脚本当作入口；`scripts/xcode/` 是内部模块，不直接执行。",
    "优先走无障碍树：先 `scripts/screen_mapper.mjs` / `scripts/navigator.mjs`，最后才用坐标。",
    "大多数脚本在未传 `--udid` 时会自动选择 booted simulator；`scripts/log_monitor.mjs` 例外，参数名是 `--device-udid`。",
    "`scripts/visual_diff.mjs` 直接处理 PNG；截图缩放优先使用系统 `sips`，缺失时保留原图尺寸。",
  ],
  checklist: [
    "先跑 `node scripts/sim_health_check.mjs`，确认 `xcrun`、`simctl`、Node.js 运行时可用。",
    "每次交互前先看 `scripts/screen_mapper.mjs` 或 `scripts/navigator.mjs --list`，不要盲点。",
    "需要日志时确认参数名：`scripts/log_monitor.mjs` 用 `--device-udid`，不是 `--udid`。",
    "需要脚本化输出时统一使用 `--json`；需要完整参数时直接跑对应脚本的 `--help`。",
    "交叉引用：性能瓶颈排查看 `swiftui-performance-audit`；审核流程复现看 `apple-appstore-reviewer`。",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "用截图坐标导航",
      pass: "无障碍树语义查找",
    }),
    defineAntiPattern({
      fail: "没 booted simulator 直接跑",
      pass: "先 boot",
    }),
    defineAntiPattern({
      fail: "文档穷举参数",
      pass: "--help 是真值",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  scripts: [
    "ios-simulator-skill-accessibility-audit",
    "ios-simulator-skill-app-launcher",
    "ios-simulator-skill-app-state-capture",
    "ios-simulator-skill-build-and-test",
    "ios-simulator-skill-clipboard",
    "ios-simulator-skill-gesture",
    "ios-simulator-skill-interaction-common",
    "ios-simulator-skill-keyboard",
    "ios-simulator-skill-log-monitor",
    "ios-simulator-skill-navigator",
    "ios-simulator-skill-privacy-manager",
    "ios-simulator-skill-push-notification",
    "ios-simulator-skill-screen-mapper",
    "ios-simulator-skill-screenshot-common",
    "ios-simulator-skill-sim-health-check",
    "ios-simulator-skill-sim-list",
    "ios-simulator-skill-simctl-boot",
    "ios-simulator-skill-simctl-common",
    "ios-simulator-skill-simctl-create",
    "ios-simulator-skill-simctl-delete",
    "ios-simulator-skill-simctl-erase",
    "ios-simulator-skill-simctl-shutdown",
    "ios-simulator-skill-simulator-selector",
    "ios-simulator-skill-status-bar",
    "ios-simulator-skill-test-recorder",
    "ios-simulator-skill-visual-diff",
    "ios-simulator-skill-xcode-builder",
    "ios-simulator-skill-xcode-cache",
    "ios-simulator-skill-xcode-config",
    "ios-simulator-skill-xcode-index",
    "ios-simulator-skill-xcode-reporter",
    "ios-simulator-skill-xcode-xcresult",
  ],
});
