import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineAntiPattern,
  defineSkill,
  defineSkillScript,
  defineSkillScriptRoot,
} from "../../sdk";

export const iosSimulatorSkillSkill = defineSkill({
  id: "ios-simulator-skill",
  fullName: "iOS 模拟器自动化",
  description: "当用户需要用 Simulator、xcrun simctl、设备启动、截图、安装包、日志采集或提审前自动化回归时使用。",
  useCases: [
    "需要在模拟器里构建、运行、排查 iOS 应用问题。",
    "需要通过无障碍树导航界面，而不是靠像素坐标硬点。",
    "需要抓日志、截图、UI 树、权限状态、状态栏和推送来复现问题。",
    "需要批量启动、关闭、擦除、创建或选择模拟器。",
  ],
  constraints: [
    "仅把 `scripts/` 目录下的可执行 Node 脚本当作入口；`scripts/xcode/` 是内部模块，不直接执行。",
    "优先走无障碍树：先 `scripts/screen_mapper.mjs` / `scripts/navigator.mjs`，最后才用坐标。",
    "大多数脚本在未传 `--udid` 时会自动选择 booted simulator；`scripts/log_monitor.mjs` 例外，参数名是 `--device-udid`。",
    "`scripts/visual_diff.mjs` 直接处理 PNG；截图缩放优先使用系统 `sips`，缺失时保留原图尺寸。",
  ],
  checklist: [
    "先跑 `node scripts/sim_health_check.mjs`，确认 `xcrun`、`simctl`、Node.js 运行时可用。",
    "每次交互前先看 `scripts/screen_mapper.mjs` 或 `scripts/navigator.mjs --list`，不要盲点。",
    "需要日志时确认参数名：`scripts/log_monitor.mjs` 用 `--device-udid`，不是 `--udid`。",
    "需要脚本化输出时统一使用 `--json`；需要完整参数时直接跑对应脚本的 `--help`。",
    "交叉引用：性能瓶颈排查看 `swiftui-performance-audit`；审核流程复现看 `apple-appstore-reviewer`。",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "用截图坐标导航",
      pass: "无障碍树语义查找",
    }),
    defineAntiPattern({
      fail: "没 booted simulator 直接跑",
      pass: "先 boot",
    }),
    defineAntiPattern({
      fail: "文档穷举参数",
      pass: "--help 是真值",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  scriptRoots: [
    defineSkillScriptRoot({
      source: new URL("./scripts/", import.meta.url),
      target: "scripts",
    }),
  ],
  scripts: [
    defineSkillScript({
      id: "accessibility-audit",
      entry: new URL("./scripts/accessibility_audit.mjs", import.meta.url),
      target: "scripts/accessibility_audit.mjs",
      runtime: "node",
      bundle: false,
      description: "Script accessibility_audit.mjs.",
    }),
    defineSkillScript({
      id: "app-launcher",
      entry: new URL("./scripts/app_launcher.mjs", import.meta.url),
      target: "scripts/app_launcher.mjs",
      runtime: "node",
      bundle: false,
      description: "Script app_launcher.mjs.",
    }),
    defineSkillScript({
      id: "app-state-capture",
      entry: new URL("./scripts/app_state_capture.mjs", import.meta.url),
      target: "scripts/app_state_capture.mjs",
      runtime: "node",
      bundle: false,
      description: "Script app_state_capture.mjs.",
    }),
    defineSkillScript({
      id: "build-and-test",
      entry: new URL("./scripts/build_and_test.mjs", import.meta.url),
      target: "scripts/build_and_test.mjs",
      runtime: "node",
      bundle: false,
      description: "Script build_and_test.mjs.",
    }),
    defineSkillScript({
      id: "clipboard",
      entry: new URL("./scripts/clipboard.mjs", import.meta.url),
      target: "scripts/clipboard.mjs",
      runtime: "node",
      bundle: false,
      description: "Script clipboard.mjs.",
    }),
    defineSkillScript({
      id: "gesture",
      entry: new URL("./scripts/gesture.mjs", import.meta.url),
      target: "scripts/gesture.mjs",
      runtime: "node",
      bundle: false,
      description: "Script gesture.mjs.",
    }),
    defineSkillScript({
      id: "interaction-common",
      entry: new URL("./scripts/interaction_common.mjs", import.meta.url),
      target: "scripts/interaction_common.mjs",
      runtime: "node",
      bundle: false,
      description: "Script interaction_common.mjs.",
    }),
    defineSkillScript({
      id: "keyboard",
      entry: new URL("./scripts/keyboard.mjs", import.meta.url),
      target: "scripts/keyboard.mjs",
      runtime: "node",
      bundle: false,
      description: "Script keyboard.mjs.",
    }),
    defineSkillScript({
      id: "log-monitor",
      entry: new URL("./scripts/log_monitor.mjs", import.meta.url),
      target: "scripts/log_monitor.mjs",
      runtime: "node",
      bundle: false,
      description: "Script log_monitor.mjs.",
    }),
    defineSkillScript({
      id: "navigator",
      entry: new URL("./scripts/navigator.mjs", import.meta.url),
      target: "scripts/navigator.mjs",
      runtime: "node",
      bundle: false,
      description: "Script navigator.mjs.",
    }),
    defineSkillScript({
      id: "privacy-manager",
      entry: new URL("./scripts/privacy_manager.mjs", import.meta.url),
      target: "scripts/privacy_manager.mjs",
      runtime: "node",
      bundle: false,
      description: "Script privacy_manager.mjs.",
    }),
    defineSkillScript({
      id: "push-notification",
      entry: new URL("./scripts/push_notification.mjs", import.meta.url),
      target: "scripts/push_notification.mjs",
      runtime: "node",
      bundle: false,
      description: "Script push_notification.mjs.",
    }),
    defineSkillScript({
      id: "screen-mapper",
      entry: new URL("./scripts/screen_mapper.mjs", import.meta.url),
      target: "scripts/screen_mapper.mjs",
      runtime: "node",
      bundle: false,
      description: "Script screen_mapper.mjs.",
    }),
    defineSkillScript({
      id: "screenshot-common",
      entry: new URL("./scripts/screenshot_common.mjs", import.meta.url),
      target: "scripts/screenshot_common.mjs",
      runtime: "node",
      bundle: false,
      description: "Script screenshot_common.mjs.",
    }),
    defineSkillScript({
      id: "sim-health-check",
      entry: new URL("./scripts/sim_health_check.mjs", import.meta.url),
      target: "scripts/sim_health_check.mjs",
      runtime: "node",
      bundle: false,
      description: "Script sim_health_check.mjs.",
    }),
    defineSkillScript({
      id: "sim-list",
      entry: new URL("./scripts/sim_list.mjs", import.meta.url),
      target: "scripts/sim_list.mjs",
      runtime: "node",
      bundle: false,
      description: "Script sim_list.mjs.",
    }),
    defineSkillScript({
      id: "simctl-boot",
      entry: new URL("./scripts/simctl_boot.mjs", import.meta.url),
      target: "scripts/simctl_boot.mjs",
      runtime: "node",
      bundle: false,
      description: "Script simctl_boot.mjs.",
    }),
    defineSkillScript({
      id: "simctl-common",
      entry: new URL("./scripts/simctl_common.mjs", import.meta.url),
      target: "scripts/simctl_common.mjs",
      runtime: "node",
      bundle: false,
      description: "Script simctl_common.mjs.",
    }),
    defineSkillScript({
      id: "simctl-create",
      entry: new URL("./scripts/simctl_create.mjs", import.meta.url),
      target: "scripts/simctl_create.mjs",
      runtime: "node",
      bundle: false,
      description: "Script simctl_create.mjs.",
    }),
    defineSkillScript({
      id: "simctl-delete",
      entry: new URL("./scripts/simctl_delete.mjs", import.meta.url),
      target: "scripts/simctl_delete.mjs",
      runtime: "node",
      bundle: false,
      description: "Script simctl_delete.mjs.",
    }),
    defineSkillScript({
      id: "simctl-erase",
      entry: new URL("./scripts/simctl_erase.mjs", import.meta.url),
      target: "scripts/simctl_erase.mjs",
      runtime: "node",
      bundle: false,
      description: "Script simctl_erase.mjs.",
    }),
    defineSkillScript({
      id: "simctl-shutdown",
      entry: new URL("./scripts/simctl_shutdown.mjs", import.meta.url),
      target: "scripts/simctl_shutdown.mjs",
      runtime: "node",
      bundle: false,
      description: "Script simctl_shutdown.mjs.",
    }),
    defineSkillScript({
      id: "simulator-selector",
      entry: new URL("./scripts/simulator_selector.mjs", import.meta.url),
      target: "scripts/simulator_selector.mjs",
      runtime: "node",
      bundle: false,
      description: "Script simulator_selector.mjs.",
    }),
    defineSkillScript({
      id: "status-bar",
      entry: new URL("./scripts/status_bar.mjs", import.meta.url),
      target: "scripts/status_bar.mjs",
      runtime: "node",
      bundle: false,
      description: "Script status_bar.mjs.",
    }),
    defineSkillScript({
      id: "test-recorder",
      entry: new URL("./scripts/test_recorder.mjs", import.meta.url),
      target: "scripts/test_recorder.mjs",
      runtime: "node",
      bundle: false,
      description: "Script test_recorder.mjs.",
    }),
    defineSkillScript({
      id: "visual-diff",
      entry: new URL("./scripts/visual_diff.mjs", import.meta.url),
      target: "scripts/visual_diff.mjs",
      runtime: "node",
      bundle: false,
      description: "Script visual_diff.mjs.",
    }),
    defineSkillScript({
      id: "xcode-builder",
      entry: new URL("./scripts/xcode/builder.mjs", import.meta.url),
      target: "scripts/xcode/builder.mjs",
      runtime: "node",
      bundle: false,
      description: "Script xcode/builder.mjs.",
    }),
    defineSkillScript({
      id: "xcode-cache",
      entry: new URL("./scripts/xcode/cache.mjs", import.meta.url),
      target: "scripts/xcode/cache.mjs",
      runtime: "node",
      bundle: false,
      description: "Script xcode/cache.mjs.",
    }),
    defineSkillScript({
      id: "xcode-config",
      entry: new URL("./scripts/xcode/config.mjs", import.meta.url),
      target: "scripts/xcode/config.mjs",
      runtime: "node",
      bundle: false,
      description: "Script xcode/config.mjs.",
    }),
    defineSkillScript({
      id: "xcode-index",
      entry: new URL("./scripts/xcode/index.mjs", import.meta.url),
      target: "scripts/xcode/index.mjs",
      runtime: "node",
      bundle: false,
      description: "Script xcode/index.mjs.",
    }),
    defineSkillScript({
      id: "xcode-reporter",
      entry: new URL("./scripts/xcode/reporter.mjs", import.meta.url),
      target: "scripts/xcode/reporter.mjs",
      runtime: "node",
      bundle: false,
      description: "Script xcode/reporter.mjs.",
    }),
    defineSkillScript({
      id: "xcode-xcresult",
      entry: new URL("./scripts/xcode/xcresult.mjs", import.meta.url),
      target: "scripts/xcode/xcresult.mjs",
      runtime: "node",
      bundle: false,
      description: "Script xcode/xcresult.mjs.",
    })
  ],
});
