import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const refactoringPatternsSkill = defineSkill({
  id: "refactoring-patterns",
  fullName: "refactoring-patterns",
  description: "当用户要选择命名化重构手法、处理代码异味或在不改行为下改结构时使用。纯格式整理或单次重命名不需要。",
  useCases: [
    "适合需要明确\"该用哪个重构动作、按什么顺序做\"的情况。",
    "适合在复杂函数、重复逻辑、条件分支和数据组织问题上做精准整改。",
    "本 skill 只回答「该选哪个手法、动作序列怎么排」；流程门禁（测试基线、范围界定、回滚）由 `coding-expert/refactoring-checklist` 负责。",
    "交叉引用：整体简化用 `complexity-reducer`；设计原则校验用 `software-design`。",
  ],
  constraints: [
    "重构默认不改行为；若必须改行为，要明确拆成“重构”和“行为变更”两步。",
    "优先选最小、安全、可验证的重构序列，而不是一次跳大步。",
    "必须先识别异味，再选手法；不要为了秀技巧强行套模式。",
    "没有验证路径的高风险重构，默认不能一次完成。",
  ],
  checklist: [
    "是否先说清楚代码异味和目标状态。",
    "是否给出可落地的重构序列而非抽象建议。",
    "是否标记需要补测试或人工验证的高风险步骤。",
    "是否避免把多个重构意图塞进一次改动。",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "composing-methods",
      source: new URL("./references/composing-methods.md", import.meta.url),
      target: "references/composing-methods.md",
      title: "composing-methods.md",
      summary: "Reference material for refactoring-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "moving-features",
      source: new URL("./references/moving-features.md", import.meta.url),
      target: "references/moving-features.md",
      title: "moving-features.md",
      summary: "Reference material for refactoring-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "organizing-data",
      source: new URL("./references/organizing-data.md", import.meta.url),
      target: "references/organizing-data.md",
      title: "organizing-data.md",
      summary: "Reference material for refactoring-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "refactoring-workflow",
      source: new URL("./references/refactoring-workflow.md", import.meta.url),
      target: "references/refactoring-workflow.md",
      title: "refactoring-workflow.md",
      summary: "Reference material for refactoring-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "seam-ripper",
      source: new URL("./references/seam-ripper.md", import.meta.url),
      target: "references/seam-ripper.md",
      title: "seam-ripper.md",
      summary: "Reference material for refactoring-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "simplifying-conditionals",
      source: new URL("./references/simplifying-conditionals.md", import.meta.url),
      target: "references/simplifying-conditionals.md",
      title: "simplifying-conditionals.md",
      summary: "Reference material for refactoring-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "smell-catalog",
      source: new URL("./references/smell-catalog.md", import.meta.url),
      target: "references/smell-catalog.md",
      title: "smell-catalog.md",
      summary: "Reference material for refactoring-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
