import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
  defineSkillScript,
  defineSkillScriptRoot,
} from "../../sdk";

export const androidDeviceAutomationSkill = defineSkill({
  id: "android-device-automation",
  fullName: "Android 真机/模拟器自动化",
  description: "当用户要启动、操作或管理 Android 真机/模拟器、自动化构建部署、查看设备日志或做 UI 导航时使用。",
  useCases: [
    "当用户要启动、操作或管理 Android 真机/模拟器、自动化构建部署、查看设备日志或做 UI 导航时使用。",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  scriptRoots: [
    defineSkillScriptRoot({
      source: new URL("./scripts/", import.meta.url),
      target: "scripts",
    }),
  ],
  scripts: [
    defineSkillScript({
      id: "app-launcher",
      entry: new URL("./scripts/app_launcher.mjs", import.meta.url),
      target: "scripts/app_launcher.mjs",
      runtime: "node",
      bundle: false,
      description: "Script app_launcher.mjs.",
    }),
    defineSkillScript({
      id: "build-and-test",
      entry: new URL("./scripts/build_and_test.mjs", import.meta.url),
      target: "scripts/build_and_test.mjs",
      runtime: "node",
      bundle: false,
      description: "Script build_and_test.mjs.",
    }),
    defineSkillScript({
      id: "common",
      entry: new URL("./scripts/common.mjs", import.meta.url),
      target: "scripts/common.mjs",
      runtime: "node",
      bundle: false,
      description: "Script common.mjs.",
    }),
    defineSkillScript({
      id: "diagnose-app",
      entry: new URL("./scripts/diagnose_app.mjs", import.meta.url),
      target: "scripts/diagnose_app.mjs",
      runtime: "node",
      bundle: false,
      description: "Script diagnose_app.mjs.",
    }),
    defineSkillScript({
      id: "emu-health-check",
      entry: new URL("./scripts/emu_health_check.mjs", import.meta.url),
      target: "scripts/emu_health_check.mjs",
      runtime: "node",
      bundle: false,
      description: "Script emu_health_check.mjs.",
    }),
    defineSkillScript({
      id: "emulator-manage",
      entry: new URL("./scripts/emulator_manage.mjs", import.meta.url),
      target: "scripts/emulator_manage.mjs",
      runtime: "node",
      bundle: false,
      description: "Script emulator_manage.mjs.",
    }),
    defineSkillScript({
      id: "gesture",
      entry: new URL("./scripts/gesture.mjs", import.meta.url),
      target: "scripts/gesture.mjs",
      runtime: "node",
      bundle: false,
      description: "Script gesture.mjs.",
    }),
    defineSkillScript({
      id: "keyboard",
      entry: new URL("./scripts/keyboard.mjs", import.meta.url),
      target: "scripts/keyboard.mjs",
      runtime: "node",
      bundle: false,
      description: "Script keyboard.mjs.",
    }),
    defineSkillScript({
      id: "log-monitor",
      entry: new URL("./scripts/log_monitor.mjs", import.meta.url),
      target: "scripts/log_monitor.mjs",
      runtime: "node",
      bundle: false,
      description: "Script log_monitor.mjs.",
    }),
    defineSkillScript({
      id: "navigator",
      entry: new URL("./scripts/navigator.mjs", import.meta.url),
      target: "scripts/navigator.mjs",
      runtime: "node",
      bundle: false,
      description: "Script navigator.mjs.",
    }),
    defineSkillScript({
      id: "screen-mapper",
      entry: new URL("./scripts/screen_mapper.mjs", import.meta.url),
      target: "scripts/screen_mapper.mjs",
      runtime: "node",
      bundle: false,
      description: "Script screen_mapper.mjs.",
    })
  ],
  references: [
    defineReference({
      id: "adb-runbook",
      source: new URL("./references/adb-runbook.md", import.meta.url),
      target: "references/adb-runbook.md",
      title: "adb-runbook.md",
      summary: "Reference material for android-device-automation.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
