import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const deepCodeReadSkill = defineSkill({
  id: "deep-code-read",
  fullName: "Deep Code Reader",
  description: "当用户要深度理解不熟悉代码库，并生成可复用的认知型 skill 文件时使用。",
  useCases: [
    "用户要深度理解陌生代码库，而不是只做快速仓库体检。",
    "用户希望把代码库知识沉淀成可复用 skill。",
    "用户能接受多轮闭卷验证，要求产出可被问答检验。",
  ],
  constraints: [
    "源码只读，全程不修改",
    "Agent 隔离：A 读码写 skill，B 读码出题，C 只读 skill 答题",
    "验证必须 100% 通过或跑满 3 轮，99% 不算通过",
    "每个模块用 task 跟踪进度",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "agent-a-prompt",
      source: new URL("./references/agent-a-prompt.md", import.meta.url),
      target: "references/agent-a-prompt.md",
      title: "agent-a-prompt.md",
      summary: "Reference material for deep-code-read.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "agent-b-prompt",
      source: new URL("./references/agent-b-prompt.md", import.meta.url),
      target: "references/agent-b-prompt.md",
      title: "agent-b-prompt.md",
      summary: "Reference material for deep-code-read.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "agent-c-prompt",
      source: new URL("./references/agent-c-prompt.md", import.meta.url),
      target: "references/agent-c-prompt.md",
      title: "agent-c-prompt.md",
      summary: "Reference material for deep-code-read.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "repo-analyzer",
      source: new URL("./references/repo-analyzer.md", import.meta.url),
      target: "references/repo-analyzer.md",
      title: "repo-analyzer.md",
      summary: "Reference material for deep-code-read.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "wiki-researcher",
      source: new URL("./references/wiki-researcher.md", import.meta.url),
      target: "references/wiki-researcher.md",
      title: "wiki-researcher.md",
      summary: "Reference material for deep-code-read.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "workflow",
      source: new URL("./references/workflow.md", import.meta.url),
      target: "references/workflow.md",
      title: "workflow.md",
      summary: "Reference material for deep-code-read.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
