import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const iosHigDesignSkill = defineSkill({
  id: "ios-hig-design",
  fullName: "iOS HIG 设计",
  description: "当用户要按 iOS HIG 设计 iPhone/iPad 界面、导航结构、安全区域、系统组件、触控反馈或无障碍体验时使用。",
  useCases: [
    "设计或评审 iPhone / iPad 的 SwiftUI、UIKit 界面。",
    "用户提到安全区域、Dynamic Island、导航结构、Dynamic Type、SF Symbols 或 HIG 合规。",
    "需要把“看起来像 iOS”落实到具体布局、组件和交互决策。",
  ],
  constraints: [
    "优先使用系统组件与系统导航，不要先造自定义容器。",
    "交互控件最小触控面积按 `44x44pt` 设计，并尊重 safe area。",
    "文本要使用语义字体样式并验证 Dynamic Type，不要写死字号和行高。",
    "iPhone 与 iPad 需要分别考虑信息密度、分栏与横屏，不要拿单一尺寸糊过去。",
  ],
  checklist: [
    "布局是否覆盖小屏 iPhone、刘海 / Dynamic Island、Home Indicator、横竖屏。",
    "文本是否全部使用语义样式，且在大字号下不截断关键文案。",
    "导航是否遵循 iOS 习惯：返回、编辑、搜索、sheet、popover 都有清晰归属。",
    "图标、色彩、权限弹窗前文案是否和系统语义一致。",
    "交叉引用：SwiftUI 具体实现细节看 `swiftui-ui-patterns`；液态玻璃外观看 `liquid-glass-design`；Mac 端界面看 `macos-design-guidelines`。",
    "各主题深入指南（按需读取）：",
    "[accessibility](references/accessibility.md)、[app-icons](references/app-icons.md)、[colors-depth](references/colors-depth.md)、[components](references/components.md)",
    "[gestures](references/gestures.md)、[keyboard-input](references/keyboard-input.md)、[navigation](references/navigation.md)、[privacy-permissions](references/privacy-permissions.md)",
    "[system-integration](references/system-integration.md)、[typography](references/typography.md)、[widgets-extensions](references/widgets-extensions.md)",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "accessibility",
      source: new URL("./references/accessibility.md", import.meta.url),
      target: "references/accessibility.md",
      title: "accessibility.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "app-icons",
      source: new URL("./references/app-icons.md", import.meta.url),
      target: "references/app-icons.md",
      title: "app-icons.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "colors-depth",
      source: new URL("./references/colors-depth.md", import.meta.url),
      target: "references/colors-depth.md",
      title: "colors-depth.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "components",
      source: new URL("./references/components.md", import.meta.url),
      target: "references/components.md",
      title: "components.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "gestures",
      source: new URL("./references/gestures.md", import.meta.url),
      target: "references/gestures.md",
      title: "gestures.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "keyboard-input",
      source: new URL("./references/keyboard-input.md", import.meta.url),
      target: "references/keyboard-input.md",
      title: "keyboard-input.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "navigation",
      source: new URL("./references/navigation.md", import.meta.url),
      target: "references/navigation.md",
      title: "navigation.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "privacy-permissions",
      source: new URL("./references/privacy-permissions.md", import.meta.url),
      target: "references/privacy-permissions.md",
      title: "privacy-permissions.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "system-integration",
      source: new URL("./references/system-integration.md", import.meta.url),
      target: "references/system-integration.md",
      title: "system-integration.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "typography",
      source: new URL("./references/typography.md", import.meta.url),
      target: "references/typography.md",
      title: "typography.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "widgets-extensions",
      source: new URL("./references/widgets-extensions.md", import.meta.url),
      target: "references/widgets-extensions.md",
      title: "widgets-extensions.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
