import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const iosHigDesignSkill = defineSkill({
  id: "ios-hig-design",
  description: "当用户要按 iOS HIG 设计 iPhone/iPad 界面、导航结构、安全区域、系统组件、触控反馈或无障碍体验时使用。",
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "accessibility",
      source: new URL("./references/accessibility.md", import.meta.url),
      target: "references/accessibility.md",
      title: "accessibility.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "app-icons",
      source: new URL("./references/app-icons.md", import.meta.url),
      target: "references/app-icons.md",
      title: "app-icons.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "colors-depth",
      source: new URL("./references/colors-depth.md", import.meta.url),
      target: "references/colors-depth.md",
      title: "colors-depth.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "components",
      source: new URL("./references/components.md", import.meta.url),
      target: "references/components.md",
      title: "components.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "gestures",
      source: new URL("./references/gestures.md", import.meta.url),
      target: "references/gestures.md",
      title: "gestures.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "keyboard-input",
      source: new URL("./references/keyboard-input.md", import.meta.url),
      target: "references/keyboard-input.md",
      title: "keyboard-input.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "navigation",
      source: new URL("./references/navigation.md", import.meta.url),
      target: "references/navigation.md",
      title: "navigation.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "privacy-permissions",
      source: new URL("./references/privacy-permissions.md", import.meta.url),
      target: "references/privacy-permissions.md",
      title: "privacy-permissions.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "system-integration",
      source: new URL("./references/system-integration.md", import.meta.url),
      target: "references/system-integration.md",
      title: "system-integration.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "typography",
      source: new URL("./references/typography.md", import.meta.url),
      target: "references/typography.md",
      title: "typography.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "widgets-extensions",
      source: new URL("./references/widgets-extensions.md", import.meta.url),
      target: "references/widgets-extensions.md",
      title: "widgets-extensions.md",
      summary: "Reference material for ios-hig-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "evals",
      source: new URL("./evals/", import.meta.url),
      target: "references/evals",
      title: "Eval Cases",
      summary: "Eval cases for ios-hig-design.",
      loadWhen: "Read only when validating or improving this skill.",
    })
  ],
});
