import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineAntiPattern,
  defineSkill,
} from "../../sdk";

export const iosHigDesignSkill = defineSkill({
  id: "ios-hig-design",
  fullName: "iOS HIG 设计",
  description: "当用户要按 iOS HIG 设计 iPhone/iPad 界面、导航结构、安全区域、系统组件、触控反馈或无障碍体验时使用。",
  useCases: [
    "设计或评审 iPhone / iPad 的 SwiftUI、UIKit 界面。",
    "用户提到安全区域、Dynamic Island、导航结构、Dynamic Type、SF Symbols 或 HIG 合规。",
    "需要把“看起来像 iOS”落实到具体布局、组件和交互决策。",
  ],
  constraints: [
    "优先使用系统组件与系统导航，不要先造自定义容器。",
    "交互控件最小触控面积按 `44x44pt` 设计，并尊重 safe area。",
    "文本要使用语义字体样式并验证 Dynamic Type，不要写死字号和行高。",
    "iPhone 与 iPad 需要分别考虑信息密度、分栏与横屏，不要拿单一尺寸糊过去。",
  ],
  checklist: [
    "布局是否覆盖小屏 iPhone、刘海 / Dynamic Island、Home Indicator、横竖屏。",
    "文本是否全部使用语义样式，且在大字号下不截断关键文案。",
    "导航是否遵循 iOS 习惯：返回、编辑、搜索、sheet、popover 都有清晰归属。",
    "图标、色彩、权限弹窗前文案是否和系统语义一致。",
    "交叉引用：SwiftUI 具体实现细节看 `swiftui-ui-patterns`；液态玻璃外观看 `liquid-glass-design`；Mac 端界面看 `macos-design-guidelines`。",
    "各主题深入指南（按需读取）：",
    "[accessibility](references/accessibility.md)、[app-icons](references/app-icons.md)、[colors-depth](references/colors-depth.md)、[components](references/components.md)",
    "[gestures](references/gestures.md)、[keyboard-input](references/keyboard-input.md)、[navigation](references/navigation.md)、[privacy-permissions](references/privacy-permissions.md)",
    "[system-integration](references/system-integration.md)、[typography](references/typography.md)、[widgets-extensions](references/widgets-extensions.md)",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "固定字号忽略 Dynamic Type",
      pass: "语义字体",
    }),
    defineAntiPattern({
      fail: "首屏立即弹权限",
      pass: "先解释再请求：用 Web / Android 导航模式硬套到 iOS。 可点击区域压到 44pt 以下。",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "accessibility",
      source: new URL("./references/accessibility.md", import.meta.url),
      target: "references/accessibility.md",
      title: "accessibility.md",
      summary: "iOS 无障碍设计：VoiceOver、Dynamic Type、减少动效与辅助触控的最佳实践。",
      loadWhen: "需要确保 iOS 界面满足无障碍要求或通过审核时读取。",
    }),
    defineReference({
      id: "app-icons",
      source: new URL("./references/app-icons.md", import.meta.url),
      target: "references/app-icons.md",
      title: "app-icons.md",
      summary: "iOS App 图标设计规范：尺寸规格、圆角裁切、季节变体与审核要求。",
      loadWhen: "需要设计或提交 iOS App 图标时读取。",
    }),
    defineReference({
      id: "colors-depth",
      source: new URL("./references/colors-depth.md", import.meta.url),
      target: "references/colors-depth.md",
      title: "colors-depth.md",
      summary: "iOS 色彩系统：语义色、深浅模式适配、透明度与材质效果设计。",
      loadWhen: "需要设计 iOS 应用的色彩方案或适配深浅模式时读取。",
    }),
    defineReference({
      id: "components",
      source: new URL("./references/components.md", import.meta.url),
      target: "references/components.md",
      title: "components.md",
      summary: "iOS 系统组件指南：Navigation Bar、Tab Bar、Sheet、Alert 等标准控件的使用规范。",
      loadWhen: "需要选择或配置 iOS 系统 UI 组件时读取。",
    }),
    defineReference({
      id: "gestures",
      source: new URL("./references/gestures.md", import.meta.url),
      target: "references/gestures.md",
      title: "gestures.md",
      summary: "iOS 手势交互：轻点、滑动、捏合、长按等触控交互的设计原则。",
      loadWhen: "需要设计或审查 iOS 手势交互逻辑时读取。",
    }),
    defineReference({
      id: "keyboard-input",
      source: new URL("./references/keyboard-input.md", import.meta.url),
      target: "references/keyboard-input.md",
      title: "keyboard-input.md",
      summary: "iOS 键盘输入设计：键盘类型、return 键、输入辅助与键盘避让策略。",
      loadWhen: "需要设计 iOS 文本输入体验或键盘交互时读取。",
    }),
    defineReference({
      id: "navigation",
      source: new URL("./references/navigation.md", import.meta.url),
      target: "references/navigation.md",
      title: "navigation.md",
      summary: "iOS 导航结构：层级导航、扁平导航、内容驱动与模态呈现的设计模式。",
      loadWhen: "需要设计 iOS 应用导航架构时读取。",
    }),
    defineReference({
      id: "privacy-permissions",
      source: new URL("./references/privacy-permissions.md", import.meta.url),
      target: "references/privacy-permissions.md",
      title: "privacy-permissions.md",
      summary: "iOS 隐私权限设计：权限请求时机、文案规范与隐私保护最佳实践。",
      loadWhen: "需要设计 iOS 权限请求流程或隐私说明时读取。",
    }),
    defineReference({
      id: "system-integration",
      source: new URL("./references/system-integration.md", import.meta.url),
      target: "references/system-integration.md",
      title: "system-integration.md",
      summary: "iOS 系统集成设计：Widget、Share Sheet、Handoff、Spotlight 等系统能力集成。",
      loadWhen: "需要将 iOS 应用与系统功能深度集成时读取。",
    }),
    defineReference({
      id: "typography",
      source: new URL("./references/typography.md", import.meta.url),
      target: "references/typography.md",
      title: "typography.md",
      summary: "iOS 排版规范：SF Font、语义字体样式、行高与 Dynamic Type 适配。",
      loadWhen: "需要设计 iOS 应用的排版或验证 Dynamic Type 兼容性时读取。",
    }),
    defineReference({
      id: "widgets-extensions",
      source: new URL("./references/widgets-extensions.md", import.meta.url),
      target: "references/widgets-extensions.md",
      title: "widgets-extensions.md",
      summary: "iOS Widget 与扩展设计：Widget 尺寸、刷新策略、配置与锁屏集成。",
      loadWhen: "需要设计或开发 iOS Widget 主屏幕扩展时读取。",
    }),
  ],
});
