import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineAntiPattern,
  defineSkill,
  defineSkillGoal,
  defineSkillOutputs,
  defineSkillWorkflow,
} from "../../sdk";

export const reactNativeTurbomoduleSkill = defineSkill({
  id: "react-native-turbomodule",
  fullName: "TurboModule 开发",
  description: "当用户要创建或迁移 New Architecture TurboModule、TurboModuleRegistry、codegenConfig、JSI spec 或 typed native spec 时使用。",
  useCases: [
    "为 RN 0.76+ New Architecture 创建原生模块时。",
    "从旧 NativeModules 迁移到 TurboModule 时。",
    "需要定义 Spec、配置 Codegen 或排查类型不匹配崩溃时。",
  ],
  constraints: [
    "Spec 导出 `interface Spec extends TurboModule`，类型必须精确。",
    "`package.json` 的 `codegenConfig` 须含 `name`、`type: \"modules\"`、`jsSrcsDir`。",
    "Android：继承 Codegen 基类 + `TurboReactPackage`；禁用废弃 `ReactPackage`。",
    "iOS：`.mm` 中 `#ifdef RCT_NEW_ARCH_ENABLED` 实现 `getTurboModule:`。",
    "只用 `TurboModuleRegistry.getEnforcing<Spec>()`，不做 null 回退。",
    "异步返回 Promise；同步阻塞 JS 线程，仅限微秒级。",
    "参数类型与 Spec 不匹配时运行时崩溃而非编译报错。",
  ],
  checklist: [
    "Spec 类型是否精确，无 `any` / `Object`？",
    "Codegen 是否重跑以匹配最新 Spec？",
    "`ReactModuleInfo.className` 是否为完整限定类名？",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "Spec 用 any",
      pass: "精确类型",
    }),
    defineAntiPattern({
      fail: "Spec 改了不跑 Codegen",
      pass: "Spec 改 → Codegen 重跑",
    }),
    defineAntiPattern({
      fail: "getModule 阻塞",
      pass: "懒加载",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  sourceDir: new URL("./", import.meta.url),
  goal: defineSkillGoal({
    body: "按 React Native New Architecture 设计 typed Spec、codegen、Android/iOS 原生实现和 JS 消费层封装。",
  }),
  workflow: defineSkillWorkflow({
    steps: [
      "先确认模块能力、同步/异步边界、平台支持、错误模型、数据结构和兼容要求。",
      "读取 `spec-definition` reference 定义 TypeScript Spec、codegenConfig 和 TurboModuleRegistry 边界。",
      "Android 实现读取 `android-kotlin-impl`，iOS 实现读取 `ios-objcpp-impl`，确保命名、类型和错误处理一致。",
      "读取 `js-consumer-wrapper` reference，为业务层封装稳定 API，不让原生细节泄漏到页面。",
      "验证 codegen 产物、链接、平台编译和 JS 调用路径。",
      "输出 Spec、原生实现清单、JS wrapper、测试方法和迁移风险。",
    ],
  }),
  outputs: defineSkillOutputs({
    items: [
      "Typed Spec、codegenConfig 和 TurboModuleRegistry 设计。",
      "Android Kotlin 与 iOS ObjC++ 实现边界。",
      "JS 消费层 wrapper、错误模型和类型合同。",
      "编译/codegen/运行验证和迁移风险。",
    ],
  }),
  tools: [],
  references: [
    defineReference({
      id: "activity-system-services",
      source: new URL("./references/activity-system-services.md", import.meta.url),
      target: "references/activity-system-services.md",
      title: "activity-system-services.md",
      summary: "Android Activity/System Services 在 TurboModule 中的获取方式与生命周期管理。",
      loadWhen: "需要在 Android TurboModule 中获取 Context、Activity 或系统服务时读取。",
    }),
    defineReference({
      id: "android-kotlin-impl",
      source: new URL("./references/android-kotlin-impl.md", import.meta.url),
      target: "references/android-kotlin-impl.md",
      title: "android-kotlin-impl.md",
      summary: "Android 侧 Kotlin TurboModule 的完整实现模板与 Codegen 基类继承模式。",
      loadWhen: "需要编写 Android Kotlin TurboModule 实现或迁移旧模块到 New Architecture 时读取。",
    }),
    defineReference({
      id: "arraybuffer-zero-copy",
      source: new URL("./references/arraybuffer-zero-copy.md", import.meta.url),
      target: "references/arraybuffer-zero-copy.md",
      title: "arraybuffer-zero-copy.md",
      summary: "通过 ArrayBuffer 实现 JS 与原生之间的零拷贝数据传输方案。",
      loadWhen: "需要跨 JS/原生边界传输大量二进制数据时读取。",
    }),
    defineReference({
      id: "call-invoker-async",
      source: new URL("./references/call-invoker-async.md", import.meta.url),
      target: "references/call-invoker-async.md",
      title: "call-invoker-async.md",
      summary: "CallInvoker 异步调用模式：JS 线程与原生线程间的调度策略与注意事项。",
      loadWhen: "需要理解或调优 TurboModule 中 JS→原生线程的调用方式时读取。",
    }),
    defineReference({
      id: "cocoapods-podspec",
      source: new URL("./references/cocoapods-podspec.md", import.meta.url),
      target: "references/cocoapods-podspec.md",
      title: "cocoapods-podspec.md",
      summary: "iOS CocoaPods podspec 配置：依赖声明、编译标志与 New Architecture 兼容设置。",
      loadWhen: "需要配置 TurboModule 的 iOS podspec 文件或排查 CocoaPods 集成问题时读取。",
    }),
    defineReference({
      id: "get-turbo-module-impl",
      source: new URL("./references/get-turbo-module-impl.md", import.meta.url),
      target: "references/get-turbo-module-impl.md",
      title: "get-turbo-module-impl.md",
      summary: "iOS getTurboModule: 方法的 #ifdef RCT_NEW_ARCH_ENABLED 条件分发实现。",
      loadWhen: "需要实现 iOS 侧的 TurboModule 注册与条件编译逻辑时读取。",
    }),
    defineReference({
      id: "gradle-codegen",
      source: new URL("./references/gradle-codegen.md", import.meta.url),
      target: "references/gradle-codegen.md",
      title: "gradle-codegen.md",
      summary: "Gradle Codegen 配置：codegenConfig 声明、重跑时机与常见问题排查。",
      loadWhen: "需要配置或排查 TurboModule Codegen 的 Gradle 任务时读取。",
    }),
    defineReference({
      id: "host-object-pattern",
      source: new URL("./references/host-object-pattern.md", import.meta.url),
      target: "references/host-object-pattern.md",
      title: "host-object-pattern.md",
      summary: "JSI Host Object 模式：在原生侧暴露自定义 C++ 对象给 JS 直接调用的方式。",
      loadWhen: "需要使用 JSI HostObject 在 JS 与原生之间建立高性能直接调用时读取。",
    }),
    defineReference({
      id: "ios-objcpp-impl",
      source: new URL("./references/ios-objcpp-impl.md", import.meta.url),
      target: "references/ios-objcpp-impl.md",
      title: "ios-objcpp-impl.md",
      summary: "iOS Objective-C++ TurboModule 实现模板与 TypeScript Spec 的类型映射。",
      loadWhen: "需要编写 iOS 侧 ObjC++ TurboModule 实现或处理类型映射错误时读取。",
    }),
    defineReference({
      id: "js-consumer-wrapper",
      source: new URL("./references/js-consumer-wrapper.md", import.meta.url),
      target: "references/js-consumer-wrapper.md",
      title: "js-consumer-wrapper.md",
      summary: "JS 消费者封装：TurboModuleRegistry.getEnforcing 的类型安全调用与错误处理模式。",
      loadWhen: "需要在 JS 侧安全调用 TurboModule 或处理模块未注册的运行时错误时读取。",
    }),
    defineReference({
      id: "kotlin-turbomodule",
      source: new URL("./references/kotlin-turbomodule.md", import.meta.url),
      target: "references/kotlin-turbomodule.md",
      title: "kotlin-turbomodule.md",
      summary: "Kotlin TurboModule 特有模式：协程集成、Flow 返回值与 Android 生命周期绑定。",
      loadWhen: "需要在 Kotlin TurboModule 中使用协程或返回 Flow 给 JS 消费者时读取。",
    }),
    defineReference({
      id: "objcpp-turbomodule",
      source: new URL("./references/objcpp-turbomodule.md", import.meta.url),
      target: "references/objcpp-turbomodule.md",
      title: "objcpp-turbomodule.md",
      summary: "ObjC++ TurboModule 的详细实现模式：RCT_EXPORT_MODULE、方法导出与类型转换。",
      loadWhen: "需要编写 ObjC++ TurboModule 实现细节或排查类型转换崩溃时读取。",
    }),
    defineReference({
      id: "react-native-jsi-bridge",
      source: new URL("./references/react-native-jsi-bridge.md", import.meta.url),
      target: "references/react-native-jsi-bridge.md",
      title: "react-native-jsi-bridge.md",
      summary: "RN JSI Bridge 模式：C++ 层直接暴露 API 给 JS 的接口定义与生命周期管理。",
      loadWhen: "需要使用 JSI 在 C++ 层直接实现跨语言调用时读取。",
    }),
    defineReference({
      id: "react-native-native-module-android",
      source: new URL("./references/react-native-native-module-android.md", import.meta.url),
      target: "references/react-native-native-module-android.md",
      title: "react-native-native-module-android.md",
      summary: "Android 旧架构 NativeModule 与 TurboModule 的对比迁移指南。",
      loadWhen: "需要从旧架构 Android NativeModule 迁移到 New Architecture TurboModule 时读取。",
    }),
    defineReference({
      id: "react-native-native-module-ios",
      source: new URL("./references/react-native-native-module-ios.md", import.meta.url),
      target: "references/react-native-native-module-ios.md",
      title: "react-native-native-module-ios.md",
      summary: "iOS 旧架构 NativeModule 与 TurboModule 的对比迁移指南。",
      loadWhen: "需要从旧架构 iOS NativeModule 迁移到 New Architecture TurboModule 时读取。",
    }),
    defineReference({
      id: "spec-definition",
      source: new URL("./references/spec-definition.md", import.meta.url),
      target: "references/spec-definition.md",
      title: "spec-definition.md",
      summary: "TurboModule Spec 定义：TypeScript interface extends TurboModule 的精确类型声明与导出方式。",
      loadWhen: "需要编写或审查 TurboModule Spec 的类型定义、参数与返回值声明时读取。",
    }),
    defineReference({
      id: "swift-bridging",
      source: new URL("./references/swift-bridging.md", import.meta.url),
      target: "references/swift-bridging.md",
      title: "swift-bridging.md",
      summary: "Swift 与 ObjC++ 的桥接模式：在 Swift TurboModule 实现中调用 C++ 代码的常见方案。",
      loadWhen: "需要使用 Swift 编写 TurboModule 实现或桥接现有 C++ 逻辑时读取。",
    }),
    defineReference({
      id: "turbo-react-package",
      source: new URL("./references/turbo-react-package.md", import.meta.url),
      target: "references/turbo-react-package.md",
      title: "turbo-react-package.md",
      summary: "TurboReactPackage 注册：Android 侧模块注册与 ReactModuleInfo 类名配置。",
      loadWhen: "需要注册 Android TurboModule 到 TurboReactPackage 或排查模块未找到错误时读取。",
    }),
  ],
});
