import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk.js";

export const reactNativeTurbomoduleSkill = defineSkill({
  id: "react-native-turbomodule",
  description: "当用户要创建或迁移 New Architecture TurboModule、TurboModuleRegistry、codegenConfig、JSI spec 或 typed native spec 时使用。",
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "activity-system-services",
      source: new URL("./references/activity-system-services.md", import.meta.url),
      target: "references/activity-system-services.md",
      title: "activity-system-services.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "android-kotlin-impl",
      source: new URL("./references/android-kotlin-impl.md", import.meta.url),
      target: "references/android-kotlin-impl.md",
      title: "android-kotlin-impl.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "arraybuffer-zero-copy",
      source: new URL("./references/arraybuffer-zero-copy.md", import.meta.url),
      target: "references/arraybuffer-zero-copy.md",
      title: "arraybuffer-zero-copy.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "call-invoker-async",
      source: new URL("./references/call-invoker-async.md", import.meta.url),
      target: "references/call-invoker-async.md",
      title: "call-invoker-async.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "cocoapods-podspec",
      source: new URL("./references/cocoapods-podspec.md", import.meta.url),
      target: "references/cocoapods-podspec.md",
      title: "cocoapods-podspec.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "get-turbo-module-impl",
      source: new URL("./references/get-turbo-module-impl.md", import.meta.url),
      target: "references/get-turbo-module-impl.md",
      title: "get-turbo-module-impl.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "gradle-codegen",
      source: new URL("./references/gradle-codegen.md", import.meta.url),
      target: "references/gradle-codegen.md",
      title: "gradle-codegen.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "host-object-pattern",
      source: new URL("./references/host-object-pattern.md", import.meta.url),
      target: "references/host-object-pattern.md",
      title: "host-object-pattern.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "ios-objcpp-impl",
      source: new URL("./references/ios-objcpp-impl.md", import.meta.url),
      target: "references/ios-objcpp-impl.md",
      title: "ios-objcpp-impl.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "js-consumer-wrapper",
      source: new URL("./references/js-consumer-wrapper.md", import.meta.url),
      target: "references/js-consumer-wrapper.md",
      title: "js-consumer-wrapper.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "kotlin-turbomodule",
      source: new URL("./references/kotlin-turbomodule.md", import.meta.url),
      target: "references/kotlin-turbomodule.md",
      title: "kotlin-turbomodule.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "objcpp-turbomodule",
      source: new URL("./references/objcpp-turbomodule.md", import.meta.url),
      target: "references/objcpp-turbomodule.md",
      title: "objcpp-turbomodule.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "react-native-jsi-bridge",
      source: new URL("./references/react-native-jsi-bridge.md", import.meta.url),
      target: "references/react-native-jsi-bridge.md",
      title: "react-native-jsi-bridge.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "react-native-native-module-android",
      source: new URL("./references/react-native-native-module-android.md", import.meta.url),
      target: "references/react-native-native-module-android.md",
      title: "react-native-native-module-android.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "react-native-native-module-ios",
      source: new URL("./references/react-native-native-module-ios.md", import.meta.url),
      target: "references/react-native-native-module-ios.md",
      title: "react-native-native-module-ios.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "spec-definition",
      source: new URL("./references/spec-definition.md", import.meta.url),
      target: "references/spec-definition.md",
      title: "spec-definition.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "swift-bridging",
      source: new URL("./references/swift-bridging.md", import.meta.url),
      target: "references/swift-bridging.md",
      title: "swift-bridging.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "turbo-react-package",
      source: new URL("./references/turbo-react-package.md", import.meta.url),
      target: "references/turbo-react-package.md",
      title: "turbo-react-package.md",
      summary: "Reference material for react-native-turbomodule.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "evals",
      source: new URL("./evals/", import.meta.url),
      target: "references/evals",
      title: "Eval Cases",
      summary: "Eval cases for react-native-turbomodule.",
      loadWhen: "Read only when validating or improving this skill.",
    })
  ],
});
