import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";
import { designSystemPatternsSkill } from "../design-system-patterns/index";

export const industryDesignPresetsSkill = defineSkill({
  id: "industry-design-presets",
  fullName: "行业设计预设",
  description: "当用户要为特定行业产品选择视觉方向、配色、字体、风格或反模式时使用。",
  useCases: [
    "产品类型明确（fintech / healthcare / portfolio / gaming / spa 等），要快速锁定视觉方向。",
    "需要同时决定 风格 + 配色 + 字体对 + 关键效果 + 反模式。",
    "不知道某个行业\"不该做什么\"（比如 banking 忌 AI 紫粉渐变）。",
    "要和 `modern-web-design`、[font-pairing-library](references/font-pairing-library.md)、`design-system-patterns` 联动。",
    "详细预设查 [references/presets-catalog.md](references/presets-catalog.md)。",
  ],
  constraints: [
    "预设是**起点不是终点**：先照表落 60%，剩余 40% 由品牌差异化决定。",
    "行业语义先于视觉美感：banking 的首要情绪是\"值得托付\"，不是\"酷\"。",
    "每个行业都有反模式——选之前先看\"AVOID 清单\"。",
    "风格要和 `modern-web-design` 的 keywords 对齐，配色要和 `design-system-patterns` 的 token 对齐。",
    "不机械套用：如果产品是 \"B2B SaaS + Gen-Z 氛围\"，按\"主行业 + 次行业氛围\"叠加，不用单 preset。",
  ],
  relatedSkills: [
    {
      get id() {
        return designSystemPatternsSkill.id;
      },
      reason: "要和 `modern-web-design`、font-pairing-library、`design-system-patterns` 联动。",
    },
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "font-pairing-library",
      source: new URL("./references/font-pairing-library.md", import.meta.url),
      target: "references/font-pairing-library.md",
      title: "font-pairing-library.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "presets-catalog",
      source: new URL("./references/presets-catalog.md", import.meta.url),
      target: "references/presets-catalog.md",
      title: "presets-catalog.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "presets-events-culture",
      source: new URL("./references/presets-events-culture.md", import.meta.url),
      target: "references/presets-events-culture.md",
      title: "presets-events-culture.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "presets-finance-commerce",
      source: new URL("./references/presets-finance-commerce.md", import.meta.url),
      target: "references/presets-finance-commerce.md",
      title: "presets-finance-commerce.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "presets-health-lifestyle",
      source: new URL("./references/presets-health-lifestyle.md", import.meta.url),
      target: "references/presets-health-lifestyle.md",
      title: "presets-health-lifestyle.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "presets-local-services",
      source: new URL("./references/presets-local-services.md", import.meta.url),
      target: "references/presets-local-services.md",
      title: "presets-local-services.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "presets-media-edu-care",
      source: new URL("./references/presets-media-edu-care.md", import.meta.url),
      target: "references/presets-media-edu-care.md",
      title: "presets-media-edu-care.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "presets-mobility-realestate",
      source: new URL("./references/presets-mobility-realestate.md", import.meta.url),
      target: "references/presets-mobility-realestate.md",
      title: "presets-mobility-realestate.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "presets-productivity-consumer",
      source: new URL("./references/presets-productivity-consumer.md", import.meta.url),
      target: "references/presets-productivity-consumer.md",
      title: "presets-productivity-consumer.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "presets-services-creative",
      source: new URL("./references/presets-services-creative.md", import.meta.url),
      target: "references/presets-services-creative.md",
      title: "presets-services-creative.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "presets-tech-saas",
      source: new URL("./references/presets-tech-saas.md", import.meta.url),
      target: "references/presets-tech-saas.md",
      title: "presets-tech-saas.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "presets-youth-public",
      source: new URL("./references/presets-youth-public.md", import.meta.url),
      target: "references/presets-youth-public.md",
      title: "presets-youth-public.md",
      summary: "Reference material for industry-design-presets.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
