import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const vueExpertJsSkill = defineSkill({
  id: "vue-expert-js",
  fullName: "Vue Expert（JavaScript）",
  description: "当用户用 JavaScript 编写 Vue 3、Pinia、composable、JSDoc 或 Vite 相关代码时使用。",
  useCases: [
    "需要用纯 JavaScript 编写 Vue 3 组件、composable、Pinia store 或 Vite 配置。",
    "项目明确不启用 TypeScript，但仍要求通过 `@typedef`、`@param`、`@returns`、`@type` 保持 API 自描述。",
    "需要把 Vue 2 Options API 逐步迁移到 Vue 3 Composition API，并保持文件仍为 `.js` / `.mjs` / `.vue`。",
    "需要为 Vue JavaScript 代码补 Vitest 测试时，联动 `javascript-typescript-jest`。",
    "涉及更广义的 ES 模块、异步流程或数据变换时，联动 `modern-javascript-patterns`。",
    "需要展开某一专题时，按需查阅：\n- [JSDoc 标注参考](references/jsdoc-typing.md)\n- [Composable 模式](references/composables-patterns.md)\n- [组件结构](references/component-architecture.md)\n- [状态管理](references/state-management.md)\n- [测试模式](references/testing-patterns.md)",
  ],
  constraints: [
    "统一使用 Vue 3 Composition API 与 `<script setup>`；不要回退到 Options API 作为默认实现。",
    "禁止使用 TypeScript 语法：不写 `lang=\"ts\"`、不写 `.ts` / `.tsx`，也不在 JavaScript 文件里塞入 TS-only 语法。",
    "公开 API 必须带 JSDoc：组件 props / emits、导出函数、store action、公共 composable 返回值都要能从注释看出契约。",
    "复杂对象形状用 `@typedef` 明确声明；跨文件复用的类型通过 `import('./path').TypeName` 引用，不复制粘贴类型描述。",
    "`.mjs` 只在需要显式 ESM 边界时使用；普通浏览器端模块沿用项目既有 `.js` 约定，不为“看起来更现代”盲目改后缀。",
    "验证顺序固定为“先 JSDoc 完整，再跑测试”；测试失败时优先修逻辑或注释契约不一致，而不是弱化断言。",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "component-architecture",
      source: new URL("./references/component-architecture.md", import.meta.url),
      target: "references/component-architecture.md",
      title: "component-architecture.md",
      summary: "Reference material for vue-expert-js.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "composables-patterns",
      source: new URL("./references/composables-patterns.md", import.meta.url),
      target: "references/composables-patterns.md",
      title: "composables-patterns.md",
      summary: "Reference material for vue-expert-js.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "jsdoc-typing",
      source: new URL("./references/jsdoc-typing.md", import.meta.url),
      target: "references/jsdoc-typing.md",
      title: "jsdoc-typing.md",
      summary: "Reference material for vue-expert-js.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "state-management",
      source: new URL("./references/state-management.md", import.meta.url),
      target: "references/state-management.md",
      title: "state-management.md",
      summary: "Reference material for vue-expert-js.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "testing-patterns",
      source: new URL("./references/testing-patterns.md", import.meta.url),
      target: "references/testing-patterns.md",
      title: "testing-patterns.md",
      summary: "Reference material for vue-expert-js.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
