import {
  InvocationPolicy,
  Platform,
  defineReference,
  defineAntiPattern,
  defineSkill,
  defineSkillOutputs,
  defineWorkflow,
  defineWorkflowStep,
} from "../../sdk";
import { reactNativeDesignSkill } from "../react-native-design/index";

export const reactNativeJsPerformanceSkill = defineSkill({
  id: "react-native-js-performance",
  fullName: "React Native JS 线程性能",
  description: "当用户要排查 JS thread 性能、掉帧、FPS、FlatList、FlashList、React Compiler、内存泄漏、动画抖动或 ScrollView 慢时使用。",
  useCases: [
    "界面卡顿、滚动掉帧、动画抖动、输入延迟。",
    "大列表渲染慢，需要评估 FlatList / FlashList / 虚拟化策略。",
    "动画需要从 JS 线程迁移到 UI 线程（Reanimated worklet）。",
    "React 渲染性能分析、React Compiler 接入评估。",
    "JS 内存泄漏定位与修复。",
  ],
  constraints: [
    "量化 = 帧耗时/FPS 数字，不是\"感觉流畅了\"。用 Perf Monitor 或 Flashlight 拿到数据再下结论。",
    "只用 release 构建做真实性能判断；debug 构建的 JS 执行慢 10-20 倍，结论完全失真。",
    "区分 JS 线程瓶颈和 UI 线程瓶颈——症状相似但解法不同。Perf Monitor 左列（JS）掉帧和右列（UI）掉帧要区别对待。",
  ],
  checklist: [
    "是否用 Perf Monitor 或 Flashlight 记录了优化前后的 FPS 数据？",
    "是否在 release 构建、真机上复测？",
    "大列表是否使用虚拟化组件，并控制 `windowSize`/`initialNumToRender`？",
    "动画是否尽量放到 Reanimated/UI 线程，而不是 JS 线程？",
    "高频输入是否使用非受控组件或 deferred value？",
    "是否排查了闭包、定时器和事件监听器的内存泄漏？",
  ],
  relatedSkills: [
    {
      get id() {
        return reactNativeDesignSkill.id;
      },
      reason: "交互与视觉实现优先联动 `react-native-design`。",
    },
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "ScrollView 渲染长列表",
      pass: "虚拟化列表",
    }),
    defineAntiPattern({
      fail: "debug 构建下结论：debug 构建 JS 执行慢 10-20 倍，结论完全失真。",
      pass: "release 真机复测",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  sourceDir: new URL("./", import.meta.url),
  workflow: defineWorkflow({
    steps: [
      defineWorkflowStep({
        id: "step-1",
        label: "先在 release 构建和真机上用 Perf Monitor 或 Flashlight 记录优化前 FPS/帧耗时。",
      }),
      defineWorkflowStep({
        id: "step-2",
        label: "读取 `js-diagnosis-path` reference，根据症状选择首选参考和升级路径。",
      }),
      defineWorkflowStep({
        id: "step-3",
        label: "区分 JS 线程和 UI 线程掉帧；列表、输入、动画、页面切换、内存泄漏和首屏慢分别处理。",
      }),
      defineWorkflowStep({
        id: "step-4",
        label: "大列表先用 FlatList/FlashList 虚拟化并调 `windowSize`、`initialNumToRender`、`maxToRenderPerBatch`。",
      }),
      defineWorkflowStep({
        id: "step-5",
        label: "动画和手势优先迁移到 Reanimated/UI 线程；高频输入考虑非受控组件或 deferred value。",
      }),
      defineWorkflowStep({
        id: "step-6",
        label: "优化后在同一设备和场景复测，记录指标、剩余瓶颈和下一步。",
      }),
    ],
  }),
  outputs: defineSkillOutputs({
    items: [
      "优化前后的 FPS/帧耗时数据和测试环境。",
      "症状分类、默认怀疑和选用 reference。",
      "列表、输入、动画、渲染或内存优化动作。",
      "复测结果、残留风险和后续排查路径。",
    ],
  }),
  references: [
    defineReference({
      id: "js-diagnosis-path",
      source: new URL("./references/js-diagnosis-path.md", import.meta.url),
      target: "references/js-diagnosis-path.md",
      title: "React Native JS 性能诊断路径",
      summary: "按症状选择 React Native JS 线程性能参考资料，并包含 FlatList/deferred value 调优示例。",
      loadWhen: "需要根据卡顿症状选择性能排查路径，或快速查看列表调优代码示例时读取。",
    }),
    defineReference({
      id: "images",
      source: new URL("./references/images/", import.meta.url),
      target: "references/images",
      title: "images",
      summary: "React Native 图片加载和渲染优化相关的参考图片资料。",
      loadWhen: "需要查看图片优化相关的视觉参考或说明图时读取。",
    }),
    defineReference({
      id: "js-animations-reanimated",
      source: new URL("./references/js-animations-reanimated.md", import.meta.url),
      target: "references/js-animations-reanimated.md",
      title: "js-animations-reanimated.md",
      summary: "将 JS 线程动画迁移到 Reanimated UI 线程的实践指南。",
      loadWhen: "需要将动画从 JS 线程迁移到 UI 线程以消除掉帧时读取。",
    }),
    defineReference({
      id: "js-atomic-state",
      source: new URL("./references/js-atomic-state.md", import.meta.url),
      target: "references/js-atomic-state.md",
      title: "js-atomic-state.md",
      summary: "React Native 原子化状态管理对 JS 线程性能的影响分析与优化。",
      loadWhen: "需要评估或优化原子状态管理库对 JS 线程性能的影响时读取。",
    }),
    defineReference({
      id: "js-bottomsheet",
      source: new URL("./references/js-bottomsheet.md", import.meta.url),
      target: "references/js-bottomsheet.md",
      title: "js-bottomsheet.md",
      summary: "BottomSheet 组件在 JS 线程上的性能优化策略。",
      loadWhen: "需要排查或优化 BottomSheet 交互的性能问题时读取。",
    }),
    defineReference({
      id: "js-concurrent-react",
      source: new URL("./references/js-concurrent-react.md", import.meta.url),
      target: "references/js-concurrent-react.md",
      title: "js-concurrent-react.md",
      summary: "React Concurrent 模式在 React Native 中的性能收益与接入策略。",
      loadWhen: "需要评估 React Concurrent 模式对 RN 性能的影响时读取。",
    }),
    defineReference({
      id: "js-lists-flatlist-flashlist",
      source: new URL("./references/js-lists-flatlist-flashlist.md", import.meta.url),
      target: "references/js-lists-flatlist-flashlist.md",
      title: "js-lists-flatlist-flashlist.md",
      summary: "FlatList 与 FlashList 的虚拟化策略及性能调优指南。",
      loadWhen: "需要优化大列表滚动性能或选择虚拟化组件时读取。",
    }),
    defineReference({
      id: "js-measure-fps",
      source: new URL("./references/js-measure-fps.md", import.meta.url),
      target: "references/js-measure-fps.md",
      title: "js-measure-fps.md",
      summary: "React Native FPS 测量工具与方法，包括 Perf Monitor 和 Flashlight 的使用。",
      loadWhen: "需要量化 JS 线程帧率或做优化前后对比时读取。",
    }),
    defineReference({
      id: "js-memory-leaks",
      source: new URL("./references/js-memory-leaks.md", import.meta.url),
      target: "references/js-memory-leaks.md",
      title: "js-memory-leaks.md",
      summary: "React Native JS 线程内存泄漏的定位方法与常见泄漏模式。",
      loadWhen: "需要排查 JS 线程内存泄漏时读取。",
    }),
    defineReference({
      id: "js-profile-react",
      source: new URL("./references/js-profile-react.md", import.meta.url),
      target: "references/js-profile-react.md",
      title: "js-profile-react.md",
      summary: "React 渲染性能分析工具与方法，帮助定位不必要的重渲染。",
      loadWhen: "需要对 React 组件做渲染性能分析时读取。",
    }),
    defineReference({
      id: "js-react-compiler",
      source: new URL("./references/js-react-compiler.md", import.meta.url),
      target: "references/js-react-compiler.md",
      title: "js-react-compiler.md",
      summary: "React Compiler 在 React Native 中的接入评估与配置指南。",
      loadWhen: "需要评估或配置 React Compiler 以自动优化渲染性能时读取。",
    }),
    defineReference({
      id: "js-uncontrolled-components",
      source: new URL("./references/js-uncontrolled-components.md", import.meta.url),
      target: "references/js-uncontrolled-components.md",
      title: "js-uncontrolled-components.md",
      summary: "非受控组件在高频输入场景下的性能优势与使用策略。",
      loadWhen: "需要优化高频输入场景的 JS 线程性能时读取。",
    }),
    defineReference({
      id: "react-native-native-performance",
      source: new URL("./references/react-native-native-performance.md", import.meta.url),
      target: "references/react-native-native-performance.md",
      title: "react-native-native-performance.md",
      summary: "React Native 原生线程性能分析与优化策略。",
      loadWhen: "需要区分 JS 线程瓶颈和 UI 线程瓶颈并分别优化时读取。",
    }),
    defineReference({
      id: "native-measure-tti",
      source: new URL("./references/native-measure-tti.md", import.meta.url),
      target: "references/native-measure-tti.md",
      title: "native-measure-tti.md",
      summary: "React Native 冷启动和 TTI 测量方法。",
      loadWhen: "冷启动慢、首屏可交互时间异常或需要对比启动优化前后时读取。",
    }),
    defineReference({
      id: "native-threading-model",
      source: new URL("./references/native-threading-model.md", import.meta.url),
      target: "references/native-threading-model.md",
      title: "native-threading-model.md",
      summary: "React Native JS、UI、Native Modules 等线程模型与瓶颈定位。",
      loadWhen: "需要区分 JS 慢、UI 慢、Bridge/Native Modules 阻塞时读取。",
    }),
    defineReference({
      id: "native-view-flattening",
      source: new URL("./references/native-view-flattening.md", import.meta.url),
      target: "references/native-view-flattening.md",
      title: "native-view-flattening.md",
      summary: "View 层级压平、布局成本和页面切换卡顿优化。",
      loadWhen: "UI FPS 掉帧但 JS FPS 正常，怀疑原生视图树过深时读取。",
    }),
    defineReference({
      id: "native-profiling",
      source: new URL("./references/native-profiling.md", import.meta.url),
      target: "references/native-profiling.md",
      title: "native-profiling.md",
      summary: "Xcode Instruments 和 Android Studio Profiler 的原生性能分析流程。",
      loadWhen: "需要用火焰图、分配记录或主线程采样定位原生瓶颈时读取。",
    }),
    defineReference({
      id: "native-memory-leaks",
      source: new URL("./references/native-memory-leaks.md", import.meta.url),
      target: "references/native-memory-leaks.md",
      title: "native-memory-leaks.md",
      summary: "React Native 原生对象、监听器、Observer 和 Timer 泄漏定位。",
      loadWhen: "内存持续上涨但 JS heap 未解释问题，或怀疑原生侧泄漏时读取。",
    }),
    defineReference({
      id: "native-memory-patterns",
      source: new URL("./references/native-memory-patterns.md", import.meta.url),
      target: "references/native-memory-patterns.md",
      title: "native-memory-patterns.md",
      summary: "原生内存增长、缓存、图片和生命周期释放模式。",
      loadWhen: "需要区分正常缓存增长、泄漏和生命周期释放不及时问题时读取。",
    }),
    defineReference({
      id: "native-turbo-modules",
      source: new URL("./references/native-turbo-modules.md", import.meta.url),
      target: "references/native-turbo-modules.md",
      title: "native-turbo-modules.md",
      summary: "TurboModules 性能收益、同步方法风险和迁移评估。",
      loadWhen: "原生模块调用延迟高或需要评估 TurboModules/New Architecture 迁移时读取。",
    }),
    defineReference({
      id: "native-sdks-over-polyfills",
      source: new URL("./references/native-sdks-over-polyfills.md", import.meta.url),
      target: "references/native-sdks-over-polyfills.md",
      title: "native-sdks-over-polyfills.md",
      summary: "用原生 SDK 替代 JS polyfill 的性能判断和维护成本评估。",
      loadWhen: "JS polyfill 性能不足或需要把高频能力下沉到原生层时读取。",
    }),
    defineReference({
      id: "native-platform-setup",
      source: new URL("./references/native-platform-setup.md", import.meta.url),
      target: "references/native-platform-setup.md",
      title: "native-platform-setup.md",
      summary: "iOS/Android 原生性能排查环境、release 构建和工具准备。",
      loadWhen: "需要搭建原生性能复现环境或排除 debug 构建误判时读取。",
    }),
    defineReference({
      id: "native-android-16kb-alignment",
      source: new URL("./references/native-android-16kb-alignment.md", import.meta.url),
      target: "references/native-android-16kb-alignment.md",
      title: "native-android-16kb-alignment.md",
      summary: "Android 16KB page size 对齐检查、依赖升级和上架前验证。",
      loadWhen: "Google Play 提示 16KB page size 不兼容或上架前检查原生库对齐时读取。",
    }),
  ],
});
