import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";
import { reactNativeDesignSkill } from "../react-native-design/index";

export const reactNativeJsPerformanceSkill = defineSkill({
  id: "react-native-js-performance",
  fullName: "React Native JS 线程性能",
  description: "当用户要排查 JS thread 性能、掉帧、FPS、FlatList、FlashList、React Compiler、内存泄漏、动画抖动或 ScrollView 慢时使用。",
  useCases: [
    "界面卡顿、滚动掉帧、动画抖动、输入延迟。",
    "大列表渲染慢，需要评估 FlatList / FlashList / 虚拟化策略。",
    "动画需要从 JS 线程迁移到 UI 线程（Reanimated worklet）。",
    "React 渲染性能分析、React Compiler 接入评估。",
    "JS 内存泄漏定位与修复。",
    "交互与视觉实现优先联动 `react-native-design`。",
  ],
  constraints: [
    "量化 = 帧耗时/FPS 数字，不是\"感觉流畅了\"。用 Perf Monitor 或 Flashlight 拿到数据再下结论。",
    "只用 release 构建做真实性能判断；debug 构建的 JS 执行慢 10-20 倍，结论完全失真。",
    "区分 JS 线程瓶颈和 UI 线程瓶颈——症状相似但解法不同。Perf Monitor 左列（JS）掉帧和右列（UI）掉帧要区别对待。",
  ],
  checklist: [
    "是否用 Perf Monitor 或 Flashlight 记录了优化前后的 FPS 数据？",
    "是否在 release 构建、真机上复测？",
    "大列表是否使用虚拟化组件，并控制 `windowSize`/`initialNumToRender`？",
    "动画是否尽量放到 Reanimated/UI 线程，而不是 JS 线程？",
    "高频输入是否使用非受控组件或 deferred value？",
    "是否排查了闭包、定时器和事件监听器的内存泄漏？",
  ],
  relatedSkills: [
    {
      get id() {
        return reactNativeDesignSkill.id;
      },
      reason: "交互与视觉实现优先联动 `react-native-design`。",
    },
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "images",
      source: new URL("./references/images/", import.meta.url),
      target: "references/images",
      title: "images",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "js-animations-reanimated",
      source: new URL("./references/js-animations-reanimated.md", import.meta.url),
      target: "references/js-animations-reanimated.md",
      title: "js-animations-reanimated.md",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "js-atomic-state",
      source: new URL("./references/js-atomic-state.md", import.meta.url),
      target: "references/js-atomic-state.md",
      title: "js-atomic-state.md",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "js-bottomsheet",
      source: new URL("./references/js-bottomsheet.md", import.meta.url),
      target: "references/js-bottomsheet.md",
      title: "js-bottomsheet.md",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "js-concurrent-react",
      source: new URL("./references/js-concurrent-react.md", import.meta.url),
      target: "references/js-concurrent-react.md",
      title: "js-concurrent-react.md",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "js-lists-flatlist-flashlist",
      source: new URL("./references/js-lists-flatlist-flashlist.md", import.meta.url),
      target: "references/js-lists-flatlist-flashlist.md",
      title: "js-lists-flatlist-flashlist.md",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "js-measure-fps",
      source: new URL("./references/js-measure-fps.md", import.meta.url),
      target: "references/js-measure-fps.md",
      title: "js-measure-fps.md",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "js-memory-leaks",
      source: new URL("./references/js-memory-leaks.md", import.meta.url),
      target: "references/js-memory-leaks.md",
      title: "js-memory-leaks.md",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "js-profile-react",
      source: new URL("./references/js-profile-react.md", import.meta.url),
      target: "references/js-profile-react.md",
      title: "js-profile-react.md",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "js-react-compiler",
      source: new URL("./references/js-react-compiler.md", import.meta.url),
      target: "references/js-react-compiler.md",
      title: "js-react-compiler.md",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "js-uncontrolled-components",
      source: new URL("./references/js-uncontrolled-components.md", import.meta.url),
      target: "references/js-uncontrolled-components.md",
      title: "js-uncontrolled-components.md",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "react-native-native-performance",
      source: new URL("./references/react-native-native-performance.md", import.meta.url),
      target: "references/react-native-native-performance.md",
      title: "react-native-native-performance.md",
      summary: "Reference material for react-native-js-performance.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
