import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const salesEnablementSkill = defineSkill({
  id: "sales-enablement",
  fullName: "销售赋能材料（sales-enablement）",
  description: "当用户要创建销售材料、sales deck、one-pager、异议处理、demo script、销售手册或买家 enablement 内容时使用。",
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "buyer-persona",
      source: new URL("./references/buyer-persona.md", import.meta.url),
      target: "references/buyer-persona.md",
      title: "buyer-persona.md",
      summary: "Reference material for sales-enablement.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "cold-email",
      source: new URL("./references/cold-email.md", import.meta.url),
      target: "references/cold-email.md",
      title: "cold-email.md",
      summary: "Reference material for sales-enablement.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "demo-script",
      source: new URL("./references/demo-script.md", import.meta.url),
      target: "references/demo-script.md",
      title: "demo-script.md",
      summary: "Reference material for sales-enablement.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "objection-handling",
      source: new URL("./references/objection-handling.md", import.meta.url),
      target: "references/objection-handling.md",
      title: "objection-handling.md",
      summary: "Reference material for sales-enablement.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "one-pager",
      source: new URL("./references/one-pager.md", import.meta.url),
      target: "references/one-pager.md",
      title: "one-pager.md",
      summary: "Reference material for sales-enablement.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "proposal-template",
      source: new URL("./references/proposal-template.md", import.meta.url),
      target: "references/proposal-template.md",
      title: "proposal-template.md",
      summary: "Reference material for sales-enablement.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "roi-calculator",
      source: new URL("./references/roi-calculator.md", import.meta.url),
      target: "references/roi-calculator.md",
      title: "roi-calculator.md",
      summary: "Reference material for sales-enablement.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "sales-deck",
      source: new URL("./references/sales-deck.md", import.meta.url),
      target: "references/sales-deck.md",
      title: "sales-deck.md",
      summary: "Reference material for sales-enablement.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "evals",
      source: new URL("./evals/", import.meta.url),
      target: "references/evals",
      title: "Eval Cases",
      summary: "Eval cases for sales-enablement.",
      loadWhen: "Read only when validating or improving this skill.",
    })
  ],
});
