import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineAntiPattern,
  defineSkill,
  defineSkillOutputs,
  defineSkillWorkflow,
} from "../../sdk";

export const salesEnablementSkill = defineSkill({
  id: "sales-enablement",
  fullName: "销售赋能材料（sales-enablement）",
  description: "当用户要创建销售材料、sales deck、one-pager、异议处理、demo script、销售手册或买家 enablement 内容时使用。",
  useCases: [
    "制作 pitch deck、one-pager 或销售提案。",
    "编写异议处理文档或 demo 脚本。",
    "构建 ROI 计算器或买家画像卡。",
  ],
  constraints: [
    "**销售信任真实数据**——材料基于真实场景，不是市场部想象。",
    "**场景驱动**——锁定具体买家角色、行业和购买阶段。",
    "**30 秒可扫读**——核心信息前置，详细内容放附录。",
    "**锚定业务结果**——每页回答\"对客户生意意味着什么\"。",
  ],
  checklist: [
    "锁定了具体买家角色和购买阶段？",
    "前 30 秒能抓到核心信息？",
    "每个论点有数据或案例支撑？",
    "用客户语言而非公司术语？",
    "CTA 明确且低摩擦？",
    "差异化点是竞品做不到的？",
    "销售知道怎么用、什么时候用？",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "功能清单 deck",
      pass: "每个功能关联一个业务结果",
    }),
    defineAntiPattern({
      fail: "万能 one-pager",
      pass: "按行业或角色做版本",
    }),
    defineAntiPattern({
      fail: "虚构 ROI",
      pass: "保守假设 + 标注来源",
    }),
    defineAntiPattern({
      fail: "产品导览式 demo",
      pass: "从客户目标倒推展示顺序",
    }),
    defineAntiPattern({
      fail: "提案模板化",
      pass: "每份包含客户专属内容",
    }),
    defineAntiPattern({
      fail: "材料做完就扔",
      pass: "附带使用场景说明",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  sourceDir: new URL("./", import.meta.url),
  workflow: defineSkillWorkflow({
    steps: [
      "先锁定买家角色、行业、购买阶段、业务结果和销售使用场景。",
      "按需求选择材料：面对面演示读 `sales-deck`，会后留资读 `one-pager`，异议处理读 `objection-handling`，量化价值读 `roi-calculator`。",
      "产品演示读 `demo-script`，了解买家读 `buyer-persona`，推进签约读 `proposal-template`，冷启动触达读 `cold-email`。",
      "按买家类型定制：技术买家看架构/安全/集成，经济买家看 ROI/TCO/回收周期，内部倡导者看对比和审批材料，终端用户看日常体验。",
    ],
  }),
  outputs: defineSkillOutputs({
    items: [
      "材料类型、买家角色、购买阶段、使用场景和核心业务结果。",
      "对应 reference 的材料结构、论点、证据、CTA 和使用说明。",
      "技术买家、经济买家、内部倡导者、终端用户的定制差异。",
    ],
  }),
  tools: [],
  references: [
    defineReference({
      id: "buyer-persona",
      source: new URL("./references/buyer-persona.md", import.meta.url),
      target: "references/buyer-persona.md",
      title: "buyer-persona.md",
      summary: "买家角色画像模板，包含公司画像、买方角色、使用者角色和购买触发因素的完整结构。",
      loadWhen: "需要定义或细化买家角色画像时读取。",
    }),
    defineReference({
      id: "cold-email",
      source: new URL("./references/cold-email.md", import.meta.url),
      target: "references/cold-email.md",
      title: "cold-email.md",
      summary: "冷邮件模板与最佳实践，包含标题、正文、CTA 和跟进策略。",
      loadWhen: "需要设计冷邮件序列或外呼邮件模板时读取。",
    }),
    defineReference({
      id: "demo-script",
      source: new URL("./references/demo-script.md", import.meta.url),
      target: "references/demo-script.md",
      title: "demo-script.md",
      summary: "产品 Demo 脚本模板，按客户目标倒推展示顺序的结构化指引。",
      loadWhen: "需要编写或审查产品演示脚本时读取。",
    }),
    defineReference({
      id: "objection-handling",
      source: new URL("./references/objection-handling.md", import.meta.url),
      target: "references/objection-handling.md",
      title: "objection-handling.md",
      summary: "常见销售异议的分类与应对策略，包含话术模板和最佳实践。",
      loadWhen: "需要准备异议处理文档或培训销售团队应对常见反对意见时读取。",
    }),
    defineReference({
      id: "one-pager",
      source: new URL("./references/one-pager.md", import.meta.url),
      target: "references/one-pager.md",
      title: "one-pager.md",
      summary: "One-pager 模板与设计原则，帮助在单页内传达核心价值主张。",
      loadWhen: "需要制作产品 one-pager 或解决方案概览文档时读取。",
    }),
    defineReference({
      id: "proposal-template",
      source: new URL("./references/proposal-template.md", import.meta.url),
      target: "references/proposal-template.md",
      title: "proposal-template.md",
      summary: "销售提案模板，包含客户专属内容定制指南和结构化框架。",
      loadWhen: "需要编写客户提案或确保提案覆盖关键要素时读取。",
    }),
    defineReference({
      id: "roi-calculator",
      source: new URL("./references/roi-calculator.md", import.meta.url),
      target: "references/roi-calculator.md",
      title: "roi-calculator.md",
      summary: "ROI 计算器模板，包含保守假设、成本收益分析和来源标注方法。",
      loadWhen: "需要构建 ROI 计算器或用量化数据支撑销售话术时读取。",
    }),
    defineReference({
      id: "sales-deck",
      source: new URL("./references/sales-deck.md", import.meta.url),
      target: "references/sales-deck.md",
      title: "sales-deck.md",
      summary: "Sales deck 结构模板，按买家角色和购买阶段组织的内容框架。",
      loadWhen: "需要设计或优化 pitch deck 的页面结构和叙事逻辑时读取。",
    }),
  ],
});
