import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const nestjsLayeringPatternsSkill = defineSkill({
  id: "nestjs-layering-patterns",
  fullName: "NestJS Layering Patterns",
  description: "当需要设计或审查 NestJS 模块分层、DTO/ValidationPipe 输入边界、依赖注入或 Guard/Interceptor/Pipe 装配时使用。",
  useCases: [
    "需要创建、修改或排查 `*.module.ts`、`*.controller.ts`、`*.service.ts`、`dto/*.dto.ts`、Guard、Interceptor、Pipe、Filter。",
    "需要设计 NestJS 模块边界、依赖注入关系、REST/GraphQL 接口、Swagger 文档、认证授权或配置加载。",
    "需要同时处理 `TypeORM`、`Prisma`、`Passport/JWT`、`ConfigModule`、`class-validator`、Jest 单测或 E2E 测试。",
    "需要把 Express/原生 Node.js API 重构为 NestJS 分层结构时，先读 [Express 迁移参考](references/migration-from-express.md)。",
    "需要补强类型建模、Jest 细节或 OpenAPI 合同生成时，可联动现有技能 `typescript-type-safety`、`javascript-typescript-jest`、`openapi-spec-generation`。",
  ],
  constraints: [
    "控制器只负责协议层：参数解析、鉴权装饰器、响应码与 Swagger 注解；业务规则放在 Service/Use Case。",
    "所有输入边界都必须通过 DTO + `class-validator` + `ValidationPipe`，禁止把原始 `req.body` 直接传入服务层。",
    "统一使用构造函数注入与 `@Injectable()`；禁止手写 `new Service()` 绕过 Nest 容器。",
    "配置、密钥、端口、第三方地址必须来自 `ConfigModule` 或环境变量；禁止写死在源码与示例里。",
    "Service 层抛出明确的 HTTP/领域异常，避免返回 `null`、魔法字符串或吞异常。",
    "默认要求补单元测试；涉及控制器、路由、认证、全局管道或模块装配时，再补 Controller/E2E 验证。",
  ],
  checklist: [
    "`AppModule` 或模块级入口是否启用了 `ValidationPipe`、必要的 Guard / Interceptor / Filter。",
    "DTO 是否覆盖所有输入边界，是否使用 `readonly`、枚举、嵌套校验与类型转换。",
    "Service 是否只依赖抽象或 provider，不在运行时直接创建外部依赖实例。",
    "控制器是否声明了 `@ApiTags`、`@ApiOperation`、`@ApiResponse` 等 Swagger 注解。",
    "配置、密钥、数据库连接与第三方 SDK 初始化是否全部走配置模块。",
    "新增逻辑是否同时覆盖单测，涉及路由/认证时是否补了控制器或 E2E 测试。",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "authentication",
      source: new URL("./references/authentication.md", import.meta.url),
      target: "references/authentication.md",
      title: "authentication.md",
      summary: "Reference material for nestjs-layering-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "basic-scaffold",
      source: new URL("./references/basic-scaffold.md", import.meta.url),
      target: "references/basic-scaffold.md",
      title: "basic-scaffold.md",
      summary: "Reference material for nestjs-layering-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "controllers-routing",
      source: new URL("./references/controllers-routing.md", import.meta.url),
      target: "references/controllers-routing.md",
      title: "controllers-routing.md",
      summary: "Reference material for nestjs-layering-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "dtos-validation",
      source: new URL("./references/dtos-validation.md", import.meta.url),
      target: "references/dtos-validation.md",
      title: "dtos-validation.md",
      summary: "Reference material for nestjs-layering-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "migration-from-express",
      source: new URL("./references/migration-from-express.md", import.meta.url),
      target: "references/migration-from-express.md",
      title: "migration-from-express.md",
      summary: "Reference material for nestjs-layering-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "services-di",
      source: new URL("./references/services-di.md", import.meta.url),
      target: "references/services-di.md",
      title: "services-di.md",
      summary: "Reference material for nestjs-layering-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "testing-patterns",
      source: new URL("./references/testing-patterns.md", import.meta.url),
      target: "references/testing-patterns.md",
      title: "testing-patterns.md",
      summary: "Reference material for nestjs-layering-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
