export const ALLOWED_FRONTMATTER_KEYS = new Set(
  "acknowledgments agent allowed-tools alwaysApply argument-hint arguments compatibility context date_added dependency description disable-model-invocation license metadata name related-skills risk source tools user-invocable user_invocable version".split(
    " ",
  ),
);
export const README_SECTION_START = "## Skill 清单";
export const README_SECTION_END = "## 数据来源";
export const STOP_WORDS = new Set([
  "a",
  "an",
  "and",
  "api",
  "app",
  "application",
  "best",
  "by",
  "code",
  "covers",
  "default",
  "for",
  "from",
  "guide",
  "help",
  "how",
  "in",
  "is",
  "it",
  "its",
  "must",
  "of",
  "on",
  "or",
  "skill",
  "skills",
  "style",
  "task",
  "tasks",
  "the",
  "this",
  "to",
  "tool",
  "tools",
  "use",
  "used",
  "using",
  "when",
  "with",
  "workflow",
]);
export const LOW_QUALITY_PATTERNS: any[] = [/\bTODO\b/i, /\bTBD\b/i, /placeholder/i];
export const EXCLUSIVE_MARKERS: any[] = [
  "must be used",
  "must use",
  "always use",
  "always prefer",
  "only",
  "do not use",
  "必须",
  "仅限",
  "只在",
  "禁止",
];
export const BROAD_SCOPE_MARKERS: any[] = [
  "any ",
  "all ",
  "must be used for",
  "always use",
  "for any",
  "任何",
  "全部",
];
export const SUMMARY_SPLIT_PATTERNS: any[] = [
  " Use when ",
  " This skill should be used when ",
  " Also use when ",
  " Triggers on ",
  " Trigger with ",
  " Use this whenever ",
  " 适合",
  " 用户提到",
  " 当用户",
];
