import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const croMethodologySkill = defineSkill({
  id: "cro-methodology",
  fullName: "转化优化方法（cro-methodology）",
  description: "在需要审计网站或落地页转化问题、梳理实验假设和设计 A/B 测试，或优化弹窗、注册流程、新手引导、AIDA 漏斗转化时使用。",
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "aida-funnel",
      source: new URL("./references/aida-funnel.md", import.meta.url),
      target: "references/aida-funnel.md",
      title: "aida-funnel.md",
      summary: "Reference material for cro-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "copywriting",
      source: new URL("./references/COPYWRITING.md", import.meta.url),
      target: "references/COPYWRITING.md",
      title: "COPYWRITING.md",
      summary: "Reference material for cro-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "funnel-analysis",
      source: new URL("./references/funnel-analysis.md", import.meta.url),
      target: "references/funnel-analysis.md",
      title: "funnel-analysis.md",
      summary: "Reference material for cro-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "objections",
      source: new URL("./references/OBJECTIONS.md", import.meta.url),
      target: "references/OBJECTIONS.md",
      title: "OBJECTIONS.md",
      summary: "Reference material for cro-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "onboarding-cro",
      source: new URL("./references/onboarding-cro.md", import.meta.url),
      target: "references/onboarding-cro.md",
      title: "onboarding-cro.md",
      summary: "Reference material for cro-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "page-cro",
      source: new URL("./references/page-cro.md", import.meta.url),
      target: "references/page-cro.md",
      title: "page-cro.md",
      summary: "Reference material for cro-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "persuasion",
      source: new URL("./references/PERSUASION.md", import.meta.url),
      target: "references/PERSUASION.md",
      title: "PERSUASION.md",
      summary: "Reference material for cro-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "popup-cro",
      source: new URL("./references/popup-cro.md", import.meta.url),
      target: "references/popup-cro.md",
      title: "popup-cro.md",
      summary: "Reference material for cro-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "research",
      source: new URL("./references/RESEARCH.md", import.meta.url),
      target: "references/RESEARCH.md",
      title: "RESEARCH.md",
      summary: "Reference material for cro-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "signup-flow-cro",
      source: new URL("./references/signup-flow-cro.md", import.meta.url),
      target: "references/signup-flow-cro.md",
      title: "signup-flow-cro.md",
      summary: "Reference material for cro-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "testing-methodology",
      source: new URL("./references/testing-methodology.md", import.meta.url),
      target: "references/testing-methodology.md",
      title: "testing-methodology.md",
      summary: "Reference material for cro-methodology.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "evals",
      source: new URL("./evals/", import.meta.url),
      target: "references/evals",
      title: "Eval Cases",
      summary: "Eval cases for cro-methodology.",
      loadWhen: "Read only when validating or improving this skill.",
    })
  ],
});
