import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const taskDecomposerSkill = defineSkill({
  id: "task-decomposer",
  fullName: "task-decomposer",
  description: "当用户要把复杂需求拆成任务板、依赖关系、关键路径或并行工作项时使用。",
  useCases: [
    "适合复杂功能、跨团队协作、需要排关键路径和并行度的实现计划。",
    "适合从模糊需求落到可执行任务，而不是只列几句待办。",
    "交叉引用：先审计划质量用 `plan-review`；需要完整功能工作流用 `feature-dev`；需要把拆解结果持久化到文件用 `persistent-planning`。",
    "当用户要为后续子代理/多 agent 执行准备计划或交接文本时，输出 Execution Contract，供 `subagent-driven-development` 消费。",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "decomposition-patterns",
      source: new URL("./references/decomposition-patterns.md", import.meta.url),
      target: "references/decomposition-patterns.md",
      title: "decomposition-patterns.md",
      summary: "Reference material for task-decomposer.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "dependency-mapping",
      source: new URL("./references/dependency-mapping.md", import.meta.url),
      target: "references/dependency-mapping.md",
      title: "dependency-mapping.md",
      summary: "Reference material for task-decomposer.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "edge-case-checklist",
      source: new URL("./references/edge-case-checklist.md", import.meta.url),
      target: "references/edge-case-checklist.md",
      title: "edge-case-checklist.md",
      summary: "Reference material for task-decomposer.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "persistent-planning",
      source: new URL("./references/persistent-planning.md", import.meta.url),
      target: "references/persistent-planning.md",
      title: "persistent-planning.md",
      summary: "Reference material for task-decomposer.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "sizing-guide",
      source: new URL("./references/sizing-guide.md", import.meta.url),
      target: "references/sizing-guide.md",
      title: "sizing-guide.md",
      summary: "Reference material for task-decomposer.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
