import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const interactionDesignSkill = defineSkill({
  id: "interaction-design",
  fullName: "交互设计",
  description: "当用户需要设计微交互、动效、过渡或反馈状态时使用。适合”加点交互感””做 loading/skeleton””优化 hover/focus/transition””让界面更顺滑”等场景。",
  useCases: [
    "为按钮、卡片、表单、导航和反馈提示增加微交互。",
    "设计页面切换、弹层展开、列表刷新等状态过渡。",
    "为加载、提交、空态、成功态和失败态设计反馈。",
    "需要把交互与性能、无障碍和品牌风格同时兼顾。",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "animation-libraries",
      source: new URL("./references/animation-libraries.md", import.meta.url),
      target: "references/animation-libraries.md",
      title: "animation-libraries.md",
      summary: "Reference material for interaction-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "lottie-animations",
      source: new URL("./references/lottie-animations.md", import.meta.url),
      target: "references/lottie-animations.md",
      title: "lottie-animations.md",
      summary: "Reference material for interaction-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "microinteraction-patterns",
      source: new URL("./references/microinteraction-patterns.md", import.meta.url),
      target: "references/microinteraction-patterns.md",
      title: "microinteraction-patterns.md",
      summary: "Reference material for interaction-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "press-and-icon-patterns",
      source: new URL("./references/press-and-icon-patterns.md", import.meta.url),
      target: "references/press-and-icon-patterns.md",
      title: "press-and-icon-patterns.md",
      summary: "Reference material for interaction-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "scroll-animations",
      source: new URL("./references/scroll-animations.md", import.meta.url),
      target: "references/scroll-animations.md",
      title: "scroll-animations.md",
      summary: "Reference material for interaction-design.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
