import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineAntiPattern,
  defineSkill,
} from "../../sdk";

export const securityThreatModelSkill = defineSkill({
  id: "security-threat-model",
  fullName: "仓库级威胁建模",
  description: "当用户要求对代码仓库做 STRIDE 分析、攻击树构建、威胁缓解映射或安全需求提取的 AppSec 威胁建模时使用。",
  useCases: [
    "需要基于仓库证据输出针对性的威胁模型，而不是通用模板。",
    "需要与 [stride-analysis-patterns](references/stride-analysis-patterns.md) 联动做系统性枚举。",
    "产出威胁后，继续用 [threat-mitigation-mapping](references/threat-mitigation-mapping.md) 和 [security-requirement-extraction](references/security-requirement-extraction.md) 落地。",
  ],
  constraints: [
    "所有组件、边界和控制都必须有仓库证据或明确假设来源。",
    "区分运行时路径与 CI/构建/开发工具，避免把辅助脚本混进主系统边界。",
    "威胁数量少而精，优先真实攻击者目标与高价值资产。",
    "当关键上下文缺失时，先提 1 到 3 个高价值问题再定级。",
  ],
  checklist: [
    "是否列出资产、边界、入口、攻击者能力和主要假设。",
    "每条威胁是否绑定具体入口和受影响资产。",
    "优先级是否说明可能性、影响和现有控制。",
    "结论是否明确区分证据、推断和待确认项。",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "没有证据直接套模板：没有引用任何仓库文件、路由或配置，纯靠假设堆砌。",
      pass: "基于仓库证据逐条建模",
    }),
    defineAntiPattern({
      fail: "不区分运行时与工具链：seed 脚本仅在开发环境运行，不是运行时攻击面。",
      pass: "明确标注路径类型",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "attack-tree-construction",
      source: new URL("./references/attack-tree-construction.md", import.meta.url),
      target: "references/attack-tree-construction.md",
      title: "attack-tree-construction.md",
      summary: "Reference material for security-threat-model.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "prompt-template",
      source: new URL("./references/prompt-template.md", import.meta.url),
      target: "references/prompt-template.md",
      title: "prompt-template.md",
      summary: "Reference material for security-threat-model.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "security-controls-and-assets",
      source: new URL("./references/security-controls-and-assets.md", import.meta.url),
      target: "references/security-controls-and-assets.md",
      title: "security-controls-and-assets.md",
      summary: "Reference material for security-threat-model.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "security-requirement-extraction",
      source: new URL("./references/security-requirement-extraction.md", import.meta.url),
      target: "references/security-requirement-extraction.md",
      title: "security-requirement-extraction.md",
      summary: "Reference material for security-threat-model.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "stride-analysis-patterns",
      source: new URL("./references/stride-analysis-patterns.md", import.meta.url),
      target: "references/stride-analysis-patterns.md",
      title: "stride-analysis-patterns.md",
      summary: "Reference material for security-threat-model.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "threat-mitigation-mapping",
      source: new URL("./references/threat-mitigation-mapping.md", import.meta.url),
      target: "references/threat-mitigation-mapping.md",
      title: "threat-mitigation-mapping.md",
      summary: "Reference material for security-threat-model.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
