import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineAntiPattern,
  defineSkill,
  defineSkillOutputs,
  defineSkillWorkflow,
} from "../../sdk";

export const securityThreatModelSkill = defineSkill({
  id: "security-threat-model",
  fullName: "仓库级威胁建模",
  description: "当用户要求对代码仓库做 STRIDE 分析、攻击树构建、威胁缓解映射或安全需求提取的 AppSec 威胁建模时使用。",
  useCases: [
    "需要基于仓库证据输出针对性的威胁模型，而不是通用模板。",
    "需要与 [stride-analysis-patterns](references/stride-analysis-patterns.md) 联动做系统性枚举。",
    "产出威胁后，继续用 [threat-mitigation-mapping](references/threat-mitigation-mapping.md) 和 [security-requirement-extraction](references/security-requirement-extraction.md) 落地。",
  ],
  constraints: [
    "所有组件、边界和控制都必须有仓库证据或明确假设来源。",
    "区分运行时路径与 CI/构建/开发工具，避免把辅助脚本混进主系统边界。",
    "威胁数量少而精，优先真实攻击者目标与高价值资产。",
    "当关键上下文缺失时，先提 1 到 3 个高价值问题再定级。",
  ],
  checklist: [
    "是否列出资产、边界、入口、攻击者能力和主要假设。",
    "每条威胁是否绑定具体入口和受影响资产。",
    "优先级是否说明可能性、影响和现有控制。",
    "结论是否明确区分证据、推断和待确认项。",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "没有证据直接套模板：没有引用任何仓库文件、路由或配置，纯靠假设堆砌。",
      pass: "基于仓库证据逐条建模",
    }),
    defineAntiPattern({
      fail: "不区分运行时与工具链：seed 脚本仅在开发环境运行，不是运行时攻击面。",
      pass: "明确标注路径类型",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  sourceDir: new URL("./", import.meta.url),
  workflow: defineSkillWorkflow({
    steps: [
      "先确认分析范围、仓库证据、关键假设和缺失上下文；上下文不足时先问 1 到 3 个高价值问题。",
      "列出资产、信任边界、入口、攻击者能力和现有控制，区分运行时路径与 CI/构建/开发工具。",
      "按 STRIDE 枚举威胁；需要系统化分类时读取 `stride-analysis-patterns` reference。",
      "对高价值资产构建攻击树；需要路径展开时读取 `attack-tree-construction` reference。",
      "把威胁映射到现有控制和缓解措施，读取 `security-controls-and-assets` 与 `threat-mitigation-mapping`。",
      "从威胁中提取安全需求，读取 `security-requirement-extraction`，并区分证据、推断和待确认项。",
    ],
  }),
  outputs: defineSkillOutputs({
    items: [
      "资产、边界、入口、攻击者能力、现有控制和假设。",
      "STRIDE 威胁清单、受影响资产、入口和证据位置。",
      "攻击树、可能性/影响/优先级和已有控制差距。",
      "缓解映射、安全需求、待确认问题和复审建议。",
    ],
  }),
  tools: [],
  references: [
    defineReference({
      id: "attack-tree-construction",
      source: new URL("./references/attack-tree-construction.md", import.meta.url),
      target: "references/attack-tree-construction.md",
      title: "attack-tree-construction.md",
      summary: "攻击树构建方法与示例，帮助系统性枚举威胁路径和攻击向量。",
      loadWhen: "需要构建攻击树以分析威胁路径或评估攻击面时读取。",
    }),
    defineReference({
      id: "prompt-template",
      source: new URL("./references/prompt-template.md", import.meta.url),
      target: "references/prompt-template.md",
      title: "prompt-template.md",
      summary: "威胁建模提示词模板，用于引导一致性威胁分析输出。",
      loadWhen: "需要标准化威胁建模输出格式或复用已验证的分析框架时读取。",
    }),
    defineReference({
      id: "security-controls-and-assets",
      source: new URL("./references/security-controls-and-assets.md", import.meta.url),
      target: "references/security-controls-and-assets.md",
      title: "security-controls-and-assets.md",
      summary: "安全控制措施与资产分类参考，包含常见控制类型和资产定级标准。",
      loadWhen: "需要映射现有安全控制到威胁或为资产分类定级时读取。",
    }),
    defineReference({
      id: "security-requirement-extraction",
      source: new URL("./references/security-requirement-extraction.md", import.meta.url),
      target: "references/security-requirement-extraction.md",
      title: "security-requirement-extraction.md",
      summary: "从威胁模型中提取可落地的安全需求的方法和模板。",
      loadWhen: "需要把威胁分析结论转化为具体的工程安全需求时读取。",
    }),
    defineReference({
      id: "stride-analysis-patterns",
      source: new URL("./references/stride-analysis-patterns.md", import.meta.url),
      target: "references/stride-analysis-patterns.md",
      title: "stride-analysis-patterns.md",
      summary: "STRIDE 威胁分类的详细模式和示例，覆盖每种威胁类别的典型场景。",
      loadWhen: "需要按 STRIDE 框架系统性枚举威胁或检查分类遗漏时读取。",
    }),
    defineReference({
      id: "threat-mitigation-mapping",
      source: new URL("./references/threat-mitigation-mapping.md", import.meta.url),
      target: "references/threat-mitigation-mapping.md",
      title: "threat-mitigation-mapping.md",
      summary: "威胁到缓解措施的映射方法，包含常见缓解模式和优先级策略。",
      loadWhen: "需要为已识别的威胁匹配合适的缓解措施和优先级时读取。",
    }),
  ],
});
