import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
  defineSkillScript,
  defineSkillScriptRoot,
} from "../../sdk";

export const pdfSkill = defineSkill({
  id: "pdf",
  fullName: "PDF",
  description: "当用户要读取、填写表单、批注、分析结构或转换 PDF 文件时使用。",
  useCases: [
    "用户要处理 `.pdf` 文件本身，而不是只抽文本。",
    "需要判断 PDF 是否可填写、提取字段信息、按 JSON 回填、或通过注释方式写入内容。",
    "需要把 PDF 渲染成图片，或根据坐标/框选信息做人工校验。",
    "纯抽取场景优先看 [pdf-extraction](references/pdf-extraction.md)。",
  ],
  constraints: [
    "先判断是“可填写表单”还是“视觉表单”，两条链路不要混用。",
    "填表前必须先跑字段发现脚本，确认字段 ID、页码和合法值。",
    "视觉型 PDF 的写入坐标要经过图片标注或抽样核对，不能凭感觉填。",
    "PDF 写回后至少人工检查一页关键字段，避免字段错位或字体异常。",
  ],
  checklist: [
    "是否区分了可填写表单与视觉型表单。",
    "是否先提取字段信息，再让用户或上游流程生成字段值 JSON。",
    "对复选框、单选组、下拉框是否检查了合法取值，而不是直接塞文本。",
    "若走视觉型写入，是否结合标注图或页面截图做了位置核验。",
    "只需抽取文本/表格时，是否切换到 [pdf-extraction](references/pdf-extraction.md)。",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  scriptRoots: [
    defineSkillScriptRoot({
      source: new URL("./scripts/", import.meta.url),
      target: "scripts",
    }),
  ],
  scripts: [
    defineSkillScript({
      id: "check-bounding-boxes",
      entry: new URL("./scripts/check_bounding_boxes.mjs", import.meta.url),
      target: "scripts/check_bounding_boxes.mjs",
      runtime: "node",
      bundle: false,
      description: "Script check_bounding_boxes.mjs.",
    }),
    defineSkillScript({
      id: "check-fillable-fields",
      entry: new URL("./scripts/check_fillable_fields.mjs", import.meta.url),
      target: "scripts/check_fillable_fields.mjs",
      runtime: "node",
      bundle: false,
      description: "Script check_fillable_fields.mjs.",
    }),
    defineSkillScript({
      id: "convert-pdf-to-images",
      entry: new URL("./scripts/convert_pdf_to_images.py", import.meta.url),
      target: "scripts/convert_pdf_to_images.py",
      runtime: "python3",
      bundle: false,
      description: "Script convert_pdf_to_images.py.",
    }),
    defineSkillScript({
      id: "create-validation-image",
      entry: new URL("./scripts/create_validation_image.py", import.meta.url),
      target: "scripts/create_validation_image.py",
      runtime: "python3",
      bundle: false,
      description: "Script create_validation_image.py.",
    }),
    defineSkillScript({
      id: "extract-form-field-info",
      entry: new URL("./scripts/extract_form_field_info.py", import.meta.url),
      target: "scripts/extract_form_field_info.py",
      runtime: "python3",
      bundle: false,
      description: "Script extract_form_field_info.py.",
    }),
    defineSkillScript({
      id: "extract-form-structure",
      entry: new URL("./scripts/extract_form_structure.py", import.meta.url),
      target: "scripts/extract_form_structure.py",
      runtime: "python3",
      bundle: false,
      description: "Script extract_form_structure.py.",
    }),
    defineSkillScript({
      id: "fill-fillable-fields",
      entry: new URL("./scripts/fill_fillable_fields.py", import.meta.url),
      target: "scripts/fill_fillable_fields.py",
      runtime: "python3",
      bundle: false,
      description: "Script fill_fillable_fields.py.",
    }),
    defineSkillScript({
      id: "fill-pdf-form-with-annotations",
      entry: new URL("./scripts/fill_pdf_form_with_annotations.py", import.meta.url),
      target: "scripts/fill_pdf_form_with_annotations.py",
      runtime: "python3",
      bundle: false,
      description: "Script fill_pdf_form_with_annotations.py.",
    })
  ],
  references: [
    defineReference({
      id: "pdf-extraction",
      source: new URL("./references/pdf-extraction.md", import.meta.url),
      target: "references/pdf-extraction.md",
      title: "pdf-extraction.md",
      summary: "Reference material for pdf.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
