import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const frontendDesignReviewSkill = defineSkill({
  id: "frontend-design-review",
  fullName: "前端设计评审",
  description: "当需要审查前端界面质量或避免 AI 套版感时使用（UI 实现层：设计还原度、可访问性、响应式、设计系统一致性）。产品策略级设计审视用 `product-design-critic`；交互可用性诊断用 `ux-heuristics`。",
  useCases: [
    "审查已实现界面的视觉质量、交互清晰度和设计系统一致性。",
    "需要对 PR、组件、页面或核心流程给出设计层面的阻塞项。",
    "需要创建风格明确、非模板化的前端界面。",
    "需要在可访问性、响应式和工程实现之间做平衡。",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "absolute-bans",
      source: new URL("./references/absolute-bans.md", import.meta.url),
      target: "references/absolute-bans.md",
      title: "absolute-bans.md",
      summary: "Reference material for frontend-design-review.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "pattern-examples",
      source: new URL("./references/pattern-examples.md", import.meta.url),
      target: "references/pattern-examples.md",
      title: "pattern-examples.md",
      summary: "Reference material for frontend-design-review.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "quick-checklist",
      source: new URL("./references/quick-checklist.md", import.meta.url),
      target: "references/quick-checklist.md",
      title: "quick-checklist.md",
      summary: "Reference material for frontend-design-review.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "review-output-format",
      source: new URL("./references/review-output-format.md", import.meta.url),
      target: "references/review-output-format.md",
      title: "review-output-format.md",
      summary: "Reference material for frontend-design-review.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "review-type-modifiers",
      source: new URL("./references/review-type-modifiers.md", import.meta.url),
      target: "references/review-type-modifiers.md",
      title: "review-type-modifiers.md",
      summary: "Reference material for frontend-design-review.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
