import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const douyinViralContentSkill = defineSkill({
  id: "douyin-viral-content",
  fullName: "抖音爆款文案生成",
  description: "当用户要创作或优化抖音短视频选题、爆款标题、口播脚本、开头钩子、分镜节奏或带货文案时使用。",
  useCases: [
    "用户只有一句金句、一本书摘录或一段主题素材，需要产出可发布的抖音文案。",
    "用户已经有历史文案样本，希望总结哪些表达更容易带来完播、互动和转发。",
    "用户提供视频摘要或逐字稿，需要二次改写成更适合短视频的口播文本。",
    "需要先提取视频内容时，使用本 skill 的视频摘要功能。",
  ],
  constraints: [
    "不要承诺“必定 5 星”或“保证爆款”；评分只能作为内部比较，不是结果保证。",
    "只有在用户明确提供历史样本、目录或表现数据时，才做校准；否则使用通用基线并明确说明。",
    "不要虚构播放量、完播率、账号体量和历史数据。",
    "输出必须保留平台安全边界，不给违规导流、虚假收益或极端承诺。",
    "当素材本身信息不足时，优先补问题，不要硬凑长文案。",
  ],
  checklist: [
    "已说明是否存在“历史样本校准”。",
    "口播脚本开头 1-2 句具备明确钩子，不绕弯。",
    "标签数量控制在 4-6 个，不堆砌。",
    "评分理由与文案结构一一对应，而不是只报分不解释。",
    "如果使用了历史数据，已标明是基于用户给定样本的归纳。",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "douyin-video-summary",
      source: new URL("./references/douyin-video-summary.md", import.meta.url),
      target: "references/douyin-video-summary.md",
      title: "douyin-video-summary.md",
      summary: "Reference material for douyin-viral-content.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "estimation-model",
      source: new URL("./references/estimation-model.md", import.meta.url),
      target: "references/estimation-model.md",
      title: "estimation-model.md",
      summary: "Reference material for douyin-viral-content.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "learning-guide",
      source: new URL("./references/learning-guide.md", import.meta.url),
      target: "references/learning-guide.md",
      title: "learning-guide.md",
      summary: "Reference material for douyin-viral-content.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "optimization-guide",
      source: new URL("./references/optimization-guide.md", import.meta.url),
      target: "references/optimization-guide.md",
      title: "optimization-guide.md",
      summary: "Reference material for douyin-viral-content.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "scoring-system",
      source: new URL("./references/scoring-system.md", import.meta.url),
      target: "references/scoring-system.md",
      title: "scoring-system.md",
      summary: "Reference material for douyin-viral-content.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "viral-factors",
      source: new URL("./references/viral-factors.md", import.meta.url),
      target: "references/viral-factors.md",
      title: "viral-factors.md",
      summary: "Reference material for douyin-viral-content.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
