import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineAntiPattern,
  defineSkill,
} from "../../sdk";

export const laravelPatternsSkill = defineSkill({
  id: "laravel-patterns",
  fullName: "Laravel 开发模式",
  description: "当用户需要处理 Laravel 分层架构、Service/Action 边界、Eloquent 模型、Migration、FormRequest、JsonResource、Job、Livewire、scopeBindings、多租户路由或 N+1 问题时使用。",
  useCases: [
    "设计或重构控制器、Action、Service、Query Object、API 资源和队列作业边界。",
    "需要从需求直接落到 Artisan 命令、Eloquent 关系、FormRequest、JsonResource 或 Livewire 组件。",
    "深入专题按需加载：`references/eloquent.md`、`routing.md`、`queues.md`、`livewire.md`、`testing.md`。",
    "架构边界/安全/测试/发布检查切换到 `laravel-security`、`laravel-tdd`、`laravel-verification`。",
  ],
  constraints: [
    "目标默认 Laravel 10+ / PHP 8.2+，使用严格类型、枚举、只读依赖和返回类型。",
    "控制器只做授权、参数接收和响应封装；校验 → `FormRequest`，序列化 → `JsonResource`，业务逻辑 → Action/Service。",
    "嵌套路由使用 `scopeBindings()`；路由绑定提升可预测性，但不能代替策略或 `authorize()`。",
    "关系查询默认 `with()` / `load()`，不要把 N+1 留给调用方。",
    "多表写操作放事务中；缓存命中必须成对设计失效策略（推荐模型事件绑定）。",
    "耗时副作用默认入队，失败路径必须可观察。",
    "API 响应统一走 `JsonResource` / `ResourceCollection`，包含 `data`、`meta`、`error` 约定字段。",
    "配置与密钥留在 `config/*` 和环境变量，禁止硬编码环境差异。",
  ],
  checklist: [
    "每个 HTTP 入口能回答：控制器/FormRequest/Action/Resource 各负责什么。",
    "嵌套资源启用 `scopeBindings()` 且 Policy 覆盖真正访问控制。",
    "模型变更同步检查 `$fillable`、`$casts`、关系、策略和资源输出。",
    "多表写操作在事务中，缓存失效绑定模型生命周期。",
    "N+1 已排查：列表/详情/嵌套资源都用了 `with()` 或 `load()`。",
    "引入后台任务时同步检查幂等、重试、失败日志和 queue 配置。",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "控制器同步编排副作用",
      pass: "Action + Job 异步",
    }),
    defineAntiPattern({
      fail: "N+1 懒加载",
      pass: "用 eager loading 或 constrained eager loading，并验证查询数。",
    }),
    defineAntiPattern({
      fail: "缓存只加不失效",
      pass: "为缓存定义失效事件、TTL 和 key version。",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "eloquent",
      source: new URL("./references/eloquent.md", import.meta.url),
      target: "references/eloquent.md",
      title: "eloquent.md",
      summary: "Reference material for laravel-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "livewire",
      source: new URL("./references/livewire.md", import.meta.url),
      target: "references/livewire.md",
      title: "livewire.md",
      summary: "Reference material for laravel-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "queues",
      source: new URL("./references/queues.md", import.meta.url),
      target: "references/queues.md",
      title: "queues.md",
      summary: "Reference material for laravel-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "routing",
      source: new URL("./references/routing.md", import.meta.url),
      target: "references/routing.md",
      title: "routing.md",
      summary: "Reference material for laravel-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "testing",
      source: new URL("./references/testing.md", import.meta.url),
      target: "references/testing.md",
      title: "testing.md",
      summary: "Reference material for laravel-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
