import {
  InvocationPolicy,
  Platform,
  defineReference,
  defineAntiPattern,
  defineSkill,
  defineSkillOutputs,
  defineWorkflow,
  defineWorkflowStep,
} from "../../sdk";

export const reactNativeMetroConfigSkill = defineSkill({
  id: "react-native-metro-config",
  fullName: "Metro 配置",
  description: "当用户要配置或排查 React Native Metro 打包器时使用。用户提到 Metro 配置、watchFolders、inlineRequires、打包慢、自定义 resolver 时触发。",
  useCases: [
    "配置 Monorepo 下 Metro 的路径解析和包发现时。",
    "添加自定义平台扩展名（.tauri.ts、.macos.ts）时。",
    "排查热更新失效、模块找不到或 CI 打包 OOM 时。",
  ],
  constraints: [
    "`inlineRequires: true` 改变初始化顺序，须充分回归测试。",
    "`watchFolders` 必须含 Monorepo 根和所有 symlink 包目录。",
    "`extraNodeModules` 用绝对路径；`react` 须指向 app 本地版本。",
    "自定义 `sourceExts` 平台特定在前、通用在后。",
    "不在 `assetExts` 中的扩展名会被当 JS 解析。",
    "CI 中 `maxWorkers` 控制在 2-4 避免 OOM。",
    "`import()` 不支持计算路径，须静态字符串。",
  ],
  checklist: [
    "`watchFolders` 是否覆盖所有 symlink 包？",
    "`react`/`react-native` 是否唯一解析到 app 版本？",
    "CI `maxWorkers` 是否已调低？",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "monorepo 漏 watchFolders",
      pass: "显式 watchFolders",
    }),
    defineAntiPattern({
      fail: "视频塞 sourceExts",
      pass: "assetExts",
    }),
    defineAntiPattern({
      fail: "CI 不限 maxWorkers",
      pass: "按环境分",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  sourceDir: new URL("./", import.meta.url),
  workflow: defineWorkflow({
    steps: [
      defineWorkflowStep({
        id: "step-1",
        label: "先确认项目结构、包管理器、workspace 边界、平台扩展、CI 环境和当前 Metro 报错/性能症状。",
      }),
      defineWorkflowStep({
        id: "step-2",
        label: "monorepo 或 workspace 问题读取 `monorepo-config` reference，核对 `watchFolders`、resolver 和重复依赖。",
      }),
      defineWorkflowStep({
        id: "step-3",
        label: "自定义平台后缀读取 `custom-platform-exts` reference，确认扩展顺序和平台目标。",
      }),
      defineWorkflowStep({
        id: "step-4",
        label: "CI 慢或缓存不稳定读取 `ci-performance-config` reference，拆分 Metro、node_modules 和构建缓存。",
      }),
      defineWorkflowStep({
        id: "step-5",
        label: "验证配置不会引入重复 React/RN、错误 symlink 解析或平台文件优先级错乱。",
      }),
      defineWorkflowStep({
        id: "step-6",
        label: "输出 Metro 配置变更、风险、验证命令和回滚方式。",
      }),
    ],
  }),
  outputs: defineSkillOutputs({
    items: [
      "Metro 问题类型、项目结构和 resolver 约束。",
      "monorepo/watchFolders/custom platform/CI 配置方案。",
      "重复依赖、平台扩展顺序和缓存风险检查。",
      "验证命令、性能对比和回滚方案。",
    ],
  }),
  references: [
    defineReference({
      id: "ci-performance-config",
      source: new URL("./references/ci-performance-config.md", import.meta.url),
      target: "references/ci-performance-config.md",
      title: "ci-performance-config.md",
      summary: "Metro 打包器在 CI 环境下的性能配置方案，包括 maxWorkers 和内存控制。",
      loadWhen: "需要优化 CI 中 Metro 打包速度或避免 OOM 时读取。",
    }),
    defineReference({
      id: "custom-platform-exts",
      source: new URL("./references/custom-platform-exts.md", import.meta.url),
      target: "references/custom-platform-exts.md",
      title: "custom-platform-exts.md",
      summary: "Metro 自定义平台扩展名的配置方法和使用规范。",
      loadWhen: "需要添加自定义平台扩展名（如 .tauri.ts、.macos.ts）时读取。",
    }),
    defineReference({
      id: "monorepo-config",
      source: new URL("./references/monorepo-config.md", import.meta.url),
      target: "references/monorepo-config.md",
      title: "monorepo-config.md",
      summary: "Monorepo 场景下 Metro 的路径解析、watchFolders 和包发现配置。",
      loadWhen: "需要配置 Monorepo 中 Metro 的路径解析和包发现时读取。",
    }),
    defineReference({
      id: "react-native-bundle-size",
      source: new URL("./references/react-native-bundle-size.md", import.meta.url),
      target: "references/react-native-bundle-size.md",
      title: "react-native-bundle-size.md",
      summary: "React Native 打包体积分析与优化策略。",
      loadWhen: "需要分析或优化 React Native 打包体积时读取。",
    }),
    defineReference({
      id: "bundle-analyze-js",
      source: new URL("./references/bundle-analyze-js.md", import.meta.url),
      target: "references/bundle-analyze-js.md",
      title: "bundle-analyze-js.md",
      summary: "使用 source-map-explorer 或 Expo Atlas 分析 JS bundle 体积。",
      loadWhen: "JS bundle 占比异常或版本升级后 JS 体积突增时读取。",
    }),
    defineReference({
      id: "bundle-barrel-exports",
      source: new URL("./references/bundle-barrel-exports.md", import.meta.url),
      target: "references/bundle-barrel-exports.md",
      title: "bundle-barrel-exports.md",
      summary: "识别 barrel exports 导致的无效依赖拉入和按路径导入优化。",
      loadWhen: "source map 显示工具库或组件库被整体打入 bundle 时读取。",
    }),
    defineReference({
      id: "bundle-tree-shaking",
      source: new URL("./references/bundle-tree-shaking.md", import.meta.url),
      target: "references/bundle-tree-shaking.md",
      title: "bundle-tree-shaking.md",
      summary: "React Native/Metro tree shaking 条件、限制和验证方式。",
      loadWhen: "需要判断未使用代码是否能被 Metro/Hermes 生产构建消除时读取。",
    }),
    defineReference({
      id: "bundle-analyze-app",
      source: new URL("./references/bundle-analyze-app.md", import.meta.url),
      target: "references/bundle-analyze-app.md",
      title: "bundle-analyze-app.md",
      summary: "拆分 APK/IPA 总体体积，区分 JS、原生库和资源占比。",
      loadWhen: "总包过大但 JS bundle 不是主要占比时读取。",
    }),
    defineReference({
      id: "bundle-native-assets",
      source: new URL("./references/bundle-native-assets.md", import.meta.url),
      target: "references/bundle-native-assets.md",
      title: "bundle-native-assets.md",
      summary: "图片、字体、视频等资源体积分析和压缩策略。",
      loadWhen: "assets/ 或资源目录占包体积大头时读取。",
    }),
    defineReference({
      id: "bundle-r8-android",
      source: new URL("./references/bundle-r8-android.md", import.meta.url),
      target: "references/bundle-r8-android.md",
      title: "bundle-r8-android.md",
      summary: "Android R8/minify/shrinkResources 配置和风险检查。",
      loadWhen: "Android 原生代码或资源过大，需要启用或调试 R8 时读取。",
    }),
    defineReference({
      id: "bundle-library-size",
      source: new URL("./references/bundle-library-size.md", import.meta.url),
      target: "references/bundle-library-size.md",
      title: "bundle-library-size.md",
      summary: "评估第三方库引入前后的 bundle 体积和替代方案。",
      loadWhen: "某个库占比异常大或新依赖引入前需要做体积评估时读取。",
    }),
    defineReference({
      id: "bundle-hermes-mmap",
      source: new URL("./references/bundle-hermes-mmap.md", import.meta.url),
      target: "references/bundle-hermes-mmap.md",
      title: "bundle-hermes-mmap.md",
      summary: "Hermes bytecode、mmap 和启动解析成本优化说明。",
      loadWhen: "启动时 JS 解析耗时长或需要评估 Hermes bytecode 优化时读取。",
    }),
    defineReference({
      id: "bundle-code-splitting",
      source: new URL("./references/bundle-code-splitting.md", import.meta.url),
      target: "references/bundle-code-splitting.md",
      title: "bundle-code-splitting.md",
      summary: "React Native 静态 import、动态 import 限制和代码拆分策略。",
      loadWhen: "需要减少首包 JS 执行/解析成本或评估延迟加载时读取。",
    }),
    defineReference({
      id: "upgrading-react-native",
      source: new URL("./references/upgrading-react-native.md", import.meta.url),
      target: "references/upgrading-react-native.md",
      title: "upgrading-react-native.md",
      summary: "React Native 版本升级指南与常见问题解决方案。",
      loadWhen: "需要规划或执行 React Native 版本升级时读取。",
    }),
  ],
});
