import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const webmanNamingConventionsSkill = defineSkill({
  id: "webman-naming-conventions",
  fullName: "Webman Naming Conventions",
  description: "当用户要统一或审查 Webman 项目的目录命名、接口后缀、Service 命名或命名空间时使用。",
  useCases: [
    "统一目录命名、接口后缀、命名空间。",
    "审查 Service/Repository 命名。",
    "修复命名空间与目录不一致。",
  ],
  constraints: [
    "目录小写，多词下划线。见 [directory-lowercase](references/directory-lowercase.md)。",
    "接口 `Interface` 后缀。见 [interface-naming](references/interface-naming.md)。",
    "Service `VerbNounService`。见 [service-naming-pattern](references/service-naming-pattern.md)。",
    "命名空间与目录一致。见 [namespace-directory-mismatch](references/namespace-directory-mismatch.md)。",
    "Repository 实现加技术前缀。见 [repository-implementation-naming](references/repository-implementation-naming.md)。",
  ],
  checklist: [
    "目录全小写，无驼峰",
    "接口用 `Interface` 后缀",
    "Service 命名表达动作",
    "命名空间与目录路径一致",
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "directory-lowercase",
      source: new URL("./references/directory-lowercase.md", import.meta.url),
      target: "references/directory-lowercase.md",
      title: "directory-lowercase.md",
      summary: "Reference material for webman-naming-conventions.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "interface-naming",
      source: new URL("./references/interface-naming.md", import.meta.url),
      target: "references/interface-naming.md",
      title: "interface-naming.md",
      summary: "Reference material for webman-naming-conventions.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "namespace-directory-mismatch",
      source: new URL("./references/namespace-directory-mismatch.md", import.meta.url),
      target: "references/namespace-directory-mismatch.md",
      title: "namespace-directory-mismatch.md",
      summary: "Reference material for webman-naming-conventions.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "repository-implementation-naming",
      source: new URL("./references/repository-implementation-naming.md", import.meta.url),
      target: "references/repository-implementation-naming.md",
      title: "repository-implementation-naming.md",
      summary: "Reference material for webman-naming-conventions.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "service-naming-pattern",
      source: new URL("./references/service-naming-pattern.md", import.meta.url),
      target: "references/service-naming-pattern.md",
      title: "service-naming-pattern.md",
      summary: "Reference material for webman-naming-conventions.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
