import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineSkill,
} from "../../sdk";

export const swiftuiUiPatternsSkill = defineSkill({
  id: "swiftui-ui-patterns",
  fullName: "SwiftUI UI 模式",
  description: "当用户需要构建、重构或拆分 SwiftUI 视图、导航、Tab 架构、组件模式或依赖注入时使用。适用于新建界面、整理视图结构、收敛 Observation 用法和查找可复用范式。",
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "app-wiring",
      source: new URL("./references/app-wiring.md", import.meta.url),
      target: "references/app-wiring.md",
      title: "app-wiring.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "components-index",
      source: new URL("./references/components-index.md", import.meta.url),
      target: "references/components-index.md",
      title: "components-index.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "controls",
      source: new URL("./references/controls.md", import.meta.url),
      target: "references/controls.md",
      title: "controls.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "deeplinks",
      source: new URL("./references/deeplinks.md", import.meta.url),
      target: "references/deeplinks.md",
      title: "deeplinks.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "focus",
      source: new URL("./references/focus.md", import.meta.url),
      target: "references/focus.md",
      title: "focus.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "form",
      source: new URL("./references/form.md", import.meta.url),
      target: "references/form.md",
      title: "form.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "grids",
      source: new URL("./references/grids.md", import.meta.url),
      target: "references/grids.md",
      title: "grids.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "haptics",
      source: new URL("./references/haptics.md", import.meta.url),
      target: "references/haptics.md",
      title: "haptics.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "input-toolbar",
      source: new URL("./references/input-toolbar.md", import.meta.url),
      target: "references/input-toolbar.md",
      title: "input-toolbar.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "lightweight-clients",
      source: new URL("./references/lightweight-clients.md", import.meta.url),
      target: "references/lightweight-clients.md",
      title: "lightweight-clients.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "list",
      source: new URL("./references/list.md", import.meta.url),
      target: "references/list.md",
      title: "list.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "loading-placeholders",
      source: new URL("./references/loading-placeholders.md", import.meta.url),
      target: "references/loading-placeholders.md",
      title: "loading-placeholders.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "macos-settings",
      source: new URL("./references/macos-settings.md", import.meta.url),
      target: "references/macos-settings.md",
      title: "macos-settings.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "matched-transitions",
      source: new URL("./references/matched-transitions.md", import.meta.url),
      target: "references/matched-transitions.md",
      title: "matched-transitions.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "media",
      source: new URL("./references/media.md", import.meta.url),
      target: "references/media.md",
      title: "media.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "menu-bar",
      source: new URL("./references/menu-bar.md", import.meta.url),
      target: "references/menu-bar.md",
      title: "menu-bar.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "mv-patterns",
      source: new URL("./references/mv-patterns.md", import.meta.url),
      target: "references/mv-patterns.md",
      title: "mv-patterns.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "navigationstack",
      source: new URL("./references/navigationstack.md", import.meta.url),
      target: "references/navigationstack.md",
      title: "navigationstack.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "overlay",
      source: new URL("./references/overlay.md", import.meta.url),
      target: "references/overlay.md",
      title: "overlay.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "scrollview",
      source: new URL("./references/scrollview.md", import.meta.url),
      target: "references/scrollview.md",
      title: "scrollview.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "searchable",
      source: new URL("./references/searchable.md", import.meta.url),
      target: "references/searchable.md",
      title: "searchable.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "sheets",
      source: new URL("./references/sheets.md", import.meta.url),
      target: "references/sheets.md",
      title: "sheets.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "split-views",
      source: new URL("./references/split-views.md", import.meta.url),
      target: "references/split-views.md",
      title: "split-views.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "tabview",
      source: new URL("./references/tabview.md", import.meta.url),
      target: "references/tabview.md",
      title: "tabview.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "theming",
      source: new URL("./references/theming.md", import.meta.url),
      target: "references/theming.md",
      title: "theming.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "title-menus",
      source: new URL("./references/title-menus.md", import.meta.url),
      target: "references/title-menus.md",
      title: "title-menus.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "top-bar",
      source: new URL("./references/top-bar.md", import.meta.url),
      target: "references/top-bar.md",
      title: "top-bar.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "view-refactoring",
      source: new URL("./references/view-refactoring.md", import.meta.url),
      target: "references/view-refactoring.md",
      title: "view-refactoring.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "evals",
      source: new URL("./evals/", import.meta.url),
      target: "references/evals",
      title: "Eval Cases",
      summary: "Eval cases for swiftui-ui-patterns.",
      loadWhen: "Read only when validating or improving this skill.",
    })
  ],
});
