import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineAntiPattern,
  defineSkill,
} from "../../sdk";

export const swiftuiUiPatternsSkill = defineSkill({
  id: "swiftui-ui-patterns",
  fullName: "SwiftUI UI 模式",
  description: "当用户需要构建、重构或拆分 SwiftUI 视图、导航、Tab 架构、组件模式或依赖注入时使用。适用于新建界面、整理视图结构、收敛 Observation 用法和查找可复用范式。",
  useCases: [
    "新建 SwiftUI 页面、Tab 架构、导航流或弹层流程。",
    "需要从现有项目中找可复用的 SwiftUI 组件模式。",
    "需要给某个界面选择合适的 `TabView`、`NavigationStack`、`sheet`、`searchable` 或 `form` 方案。",
    "需要整理视图文件顺序、拆分臃肿 `body`、收敛依赖注入或 `@Observable` 使用方式。",
    "需要把\"可选 view model + bootstrapIfNeeded\"改成可维护模式。",
  ],
  constraints: [
    "优先使用 SwiftUI 原生状态模型：`@State`、`@Binding`、`@Observable`、`@Environment`。",
    "`sheet` 状态能表达”选中了谁”时，优先用 `.sheet(item:)`，不要回退到布尔开关 + `if let`。",
    "新建页面前先读 `references/components-index.md` 和 `references/app-wiring.md`，再决定是否需要额外 reference。",
    "新增 reference 时必须是具体文件名，例如 `references/top-bar.md`，不要写占位路径。",
    "重构时先保证行为不变，再整理结构；重构不是顺手改交互。",
    "默认走 MV：视图负责状态表达和轻量编排，业务逻辑留在模型 / 服务层。",
    "如果 view model 已存在，优先让它变成非可选并在 `init` 中完成注入。",
    "需要理念展开时读取 `references/mv-patterns.md`，不要另造一套术语。",
  ],
  checklist: [
    "先从 `references/components-index.md` 选择最接近的 reference，再实现页面。",
    "新项目接线优先看 `references/app-wiring.md`；导航、分页、弹层分别看 `references/navigationstack.md`、`references/tabview.md`、`references/sheets.md`。",
    "新界面是否把状态留在最近的拥有者，而不是先造 view model。",
    "所有交互面是否有明确加载态、错误态和 dismiss / back 归属。",
    "视图文件顺序是否统一为：环境依赖 → `let` → `@State` → 非视图计算属性 → `init` → `body` → 子视图 / helper。",
    "大型 `body` 是否拆成可命名的子区域，而不是继续堆条件分支。",
    "是否移除了不必要的可选 view model、`bootstrapIfNeeded` 和重复包装。",
    "根视图是否正确持有 `@Observable`，下游只接收必要输入。",
    "交叉引用：并发边界问题看 `swift-concurrency-expert`；性能与重渲染看 `swiftui-performance-audit`；平台设计规范看 `ios-hig-design` / `macos-design-guidelines`。",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "sheet(isPresented:) + if let 解包",
      pass: "sheet(item:) 绑定数据",
    }),
    defineAntiPattern({
      fail: "小页面也造 view model",
      pass: "状态就近持有",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "app-wiring",
      source: new URL("./references/app-wiring.md", import.meta.url),
      target: "references/app-wiring.md",
      title: "app-wiring.md",
      summary: "SwiftUI 应用接线模式，包含依赖注入、环境传递和根视图初始化方法。",
      loadWhen: "需要设计新项目接线方式或重构现有应用的依赖注入体系时读取。",
    }),
    defineReference({
      id: "components-index",
      source: new URL("./references/components-index.md", import.meta.url),
      target: "references/components-index.md",
      title: "components-index.md",
      summary: "SwiftUI 可复用组件的索引目录，帮助快速找到适合的 UI 模式参考。",
      loadWhen: "需要查找可复用的 SwiftUI 组件模式或决定使用哪种 UI 方案时读取。",
    }),
    defineReference({
      id: "controls",
      source: new URL("./references/controls.md", import.meta.url),
      target: "references/controls.md",
      title: "controls.md",
      summary: "SwiftUI 常用控件的使用指南和最佳实践。",
      loadWhen: "需要了解 SwiftUI 控件的正确用法和行为差异时读取。",
    }),
    defineReference({
      id: "deeplinks",
      source: new URL("./references/deeplinks.md", import.meta.url),
      target: "references/deeplinks.md",
      title: "deeplinks.md",
      summary: "SwiftUI 应用中深度链接的处理模式与路由实现方法。",
      loadWhen: "需要实现或优化 SwiftUI 应用的深度链接和外部路由时读取。",
    }),
    defineReference({
      id: "focus",
      source: new URL("./references/focus.md", import.meta.url),
      target: "references/focus.md",
      title: "focus.md",
      summary: "SwiftUI 焦点管理指南，包含 @FocusState、键盘绑定和焦点导航模式。",
      loadWhen: "需要管理输入焦点或实现键盘导航时读取。",
    }),
    defineReference({
      id: "form",
      source: new URL("./references/form.md", import.meta.url),
      target: "references/form.md",
      title: "form.md",
      summary: "SwiftUI 表单设计模式，包含 Form、输入验证、分组和提交处理的最佳实践。",
      loadWhen: "需要设计或优化 SwiftUI 表单界面时读取。",
    }),
    defineReference({
      id: "grids",
      source: new URL("./references/grids.md", import.meta.url),
      target: "references/grids.md",
      title: "grids.md",
      summary: "SwiftUI 网格布局（LazyVGrid、LazyHGrid、Grid）的使用模式和性能考量。",
      loadWhen: "需要实现网格布局或优化网格性能时读取。",
    }),
    defineReference({
      id: "haptics",
      source: new URL("./references/haptics.md", import.meta.url),
      target: "references/haptics.md",
      title: "haptics.md",
      summary: "SwiftUI 中触觉反馈的集成方法和使用场景参考。",
      loadWhen: "需要为交互添加触觉反馈或了解不同反馈类型的使用场景时读取。",
    }),
    defineReference({
      id: "input-toolbar",
      source: new URL("./references/input-toolbar.md", import.meta.url),
      target: "references/input-toolbar.md",
      title: "input-toolbar.md",
      summary: "SwiftUI 输入工具栏（inputAccessoryView 等效）的实现模式。",
      loadWhen: "需要为键盘输入添加自定义工具栏时读取。",
    }),
    defineReference({
      id: "lightweight-clients",
      source: new URL("./references/lightweight-clients.md", import.meta.url),
      target: "references/lightweight-clients.md",
      title: "lightweight-clients.md",
      summary: "SwiftUI 轻量客户端架构模式，适用于 API 为主的简单应用。",
      loadWhen: "需要构建 API 驱动的轻量级 SwiftUI 客户端时读取。",
    }),
    defineReference({
      id: "list",
      source: new URL("./references/list.md", import.meta.url),
      target: "references/list.md",
      title: "list.md",
      summary: "SwiftUI List 的高级使用模式，包含动态行高、滑动操作、刷新和分页。",
      loadWhen: "需要实现复杂列表功能或优化列表性能时读取。",
    }),
    defineReference({
      id: "loading-placeholders",
      source: new URL("./references/loading-placeholders.md", import.meta.url),
      target: "references/loading-placeholders.md",
      title: "loading-placeholders.md",
      summary: "SwiftUI 加载占位符（skeleton、shimmer）的实现模式和最佳实践。",
      loadWhen: "需要为数据加载状态设计占位符或骨架屏时读取。",
    }),
    defineReference({
      id: "macos-settings",
      source: new URL("./references/macos-settings.md", import.meta.url),
      target: "references/macos-settings.md",
      title: "macos-settings.md",
      summary: "macOS 平台 SwiftUI 设置页面的设计模式和规范参考。",
      loadWhen: "需要开发 macOS 应用的设置界面时读取。",
    }),
    defineReference({
      id: "matched-transitions",
      source: new URL("./references/matched-transitions.md", import.meta.url),
      target: "references/matched-transitions.md",
      title: "matched-transitions.md",
      summary: "SwiftUI matchedGeometryEffect 和命名空间过渡的高级使用模式。",
      loadWhen: "需要实现视图间平滑动画过渡或自定义转场效果时读取。",
    }),
    defineReference({
      id: "media",
      source: new URL("./references/media.md", import.meta.url),
      target: "references/media.md",
      title: "media.md",
      summary: "SwiftUI 中图片、视频和音频处理的集成模式。",
      loadWhen: "需要集成图片加载、视频播放或音频控制时读取。",
    }),
    defineReference({
      id: "menu-bar",
      source: new URL("./references/menu-bar.md", import.meta.url),
      target: "references/menu-bar.md",
      title: "menu-bar.md",
      summary: "macOS 菜单栏应用的 SwiftUI 实现模式和注意事项。",
      loadWhen: "需要开发 macOS 菜单栏应用时读取。",
    }),
    defineReference({
      id: "mv-patterns",
      source: new URL("./references/mv-patterns.md", import.meta.url),
      target: "references/mv-patterns.md",
      title: "mv-patterns.md",
      summary: "SwiftUI 中 MV 架构模式的深入讲解，包含视图职责和模型层设计。",
      loadWhen: "需要理解 MV 架构理念或在 SwiftUI 中应用视图与模型分离模式时读取。",
    }),
    defineReference({
      id: "navigationstack",
      source: new URL("./references/navigationstack.md", import.meta.url),
      target: "references/navigationstack.md",
      title: "navigationstack.md",
      summary: "SwiftUI NavigationStack 的完整使用指南，包含数据驱动导航和路径管理。",
      loadWhen: "需要实现 NavigationStack 导航或管理复杂导航路径时读取。",
    }),
    defineReference({
      id: "overlay",
      source: new URL("./references/overlay.md", import.meta.url),
      target: "references/overlay.md",
      title: "overlay.md",
      summary: "SwiftUI overlay 和 ZStack 的高级使用模式，包含弹窗、提示和浮动元素。",
      loadWhen: "需要实现覆盖层、弹窗或浮动 UI 元素时读取。",
    }),
    defineReference({
      id: "scrollview",
      source: new URL("./references/scrollview.md", import.meta.url),
      target: "references/scrollview.md",
      title: "scrollview.md",
      summary: "SwiftUI ScrollView 的高级使用模式，包含滚动位置控制、分页和刷新。",
      loadWhen: "需要实现自定义滚动行为或优化 ScrollView 性能时读取。",
    }),
    defineReference({
      id: "searchable",
      source: new URL("./references/searchable.md", import.meta.url),
      target: "references/searchable.md",
      title: "searchable.md",
      summary: "SwiftUI searchable 修饰符的完整使用指南，包含搜索建议、范围和异步搜索。",
      loadWhen: "需要实现搜索功能或优化搜索体验时读取。",
    }),
    defineReference({
      id: "sheets",
      source: new URL("./references/sheets.md", import.meta.url),
      target: "references/sheets.md",
      title: "sheets.md",
      summary: "SwiftUI sheet 弹层的使用模式，包含数据绑定弹层、自适应高度和多步骤表单。",
      loadWhen: "需要选择正确的弹层方式或实现复杂的 sheet 交互时读取。",
    }),
    defineReference({
      id: "split-views",
      source: new URL("./references/split-views.md", import.meta.url),
      target: "references/split-views.md",
      title: "split-views.md",
      summary: "SwiftUI 分栏视图（NavigationSplitView）的适配模式和自适应布局策略。",
      loadWhen: "需要实现多栏布局或适配不同屏幕尺寸的分栏导航时读取。",
    }),
    defineReference({
      id: "tabview",
      source: new URL("./references/tabview.md", import.meta.url),
      target: "references/tabview.md",
      title: "tabview.md",
      summary: "SwiftUI TabView 的使用模式和最佳实践，包含多 Tab 协调和状态隔离。",
      loadWhen: "需要设计 Tab 架构或多 Tab 应用时读取。",
    }),
    defineReference({
      id: "theming",
      source: new URL("./references/theming.md", import.meta.url),
      target: "references/theming.md",
      title: "theming.md",
      summary: "SwiftUI 主题化方案，包含色彩系统、字体系统、深色模式和动态类型适配。",
      loadWhen: "需要实现应用主题切换或统一视觉风格时读取。",
    }),
    defineReference({
      id: "title-menus",
      source: new URL("./references/title-menus.md", import.meta.url),
      target: "references/title-menus.md",
      title: "title-menus.md",
      summary: "macOS 应用中标题菜单（Commands）的实现模式和规范。",
      loadWhen: "需要开发 macOS 应用的菜单命令系统时读取。",
    }),
    defineReference({
      id: "top-bar",
      source: new URL("./references/top-bar.md", import.meta.url),
      target: "references/top-bar.md",
      title: "top-bar.md",
      summary: "SwiftUI 顶部导航栏的自定义模式，包含工具栏、搜索栏和分段控制。",
      loadWhen: "需要设计自定义顶部导航栏或使用工具栏时读取。",
    }),
    defineReference({
      id: "view-refactoring",
      source: new URL("./references/view-refactoring.md", import.meta.url),
      target: "references/view-refactoring.md",
      title: "view-refactoring.md",
      summary: "SwiftUI 视图重构方法论，包含拆分臃肿 body、提取子视图和统一文件结构。",
      loadWhen: "需要重构大型 SwiftUI 视图或统一视图文件结构时读取。",
    }),
  ],
});
