import {
  InvocationPolicy,
  KnownTool,
  Platform,
  defineReference,
  defineAntiPattern,
  defineSkill,
} from "../../sdk";

export const swiftuiUiPatternsSkill = defineSkill({
  id: "swiftui-ui-patterns",
  fullName: "SwiftUI UI 模式",
  description: "当用户需要构建、重构或拆分 SwiftUI 视图、导航、Tab 架构、组件模式或依赖注入时使用。适用于新建界面、整理视图结构、收敛 Observation 用法和查找可复用范式。",
  useCases: [
    "新建 SwiftUI 页面、Tab 架构、导航流或弹层流程。",
    "需要从现有项目中找可复用的 SwiftUI 组件模式。",
    "需要给某个界面选择合适的 `TabView`、`NavigationStack`、`sheet`、`searchable` 或 `form` 方案。",
    "需要整理视图文件顺序、拆分臃肿 `body`、收敛依赖注入或 `@Observable` 使用方式。",
    "需要把\"可选 view model + bootstrapIfNeeded\"改成可维护模式。",
  ],
  constraints: [
    "优先使用 SwiftUI 原生状态模型：`@State`、`@Binding`、`@Observable`、`@Environment`。",
    "`sheet` 状态能表达”选中了谁”时，优先用 `.sheet(item:)`，不要回退到布尔开关 + `if let`。",
    "新建页面前先读 `references/components-index.md` 和 `references/app-wiring.md`，再决定是否需要额外 reference。",
    "新增 reference 时必须是具体文件名，例如 `references/top-bar.md`，不要写占位路径。",
    "重构时先保证行为不变，再整理结构；重构不是顺手改交互。",
    "默认走 MV：视图负责状态表达和轻量编排，业务逻辑留在模型 / 服务层。",
    "如果 view model 已存在，优先让它变成非可选并在 `init` 中完成注入。",
    "需要理念展开时读取 `references/mv-patterns.md`，不要另造一套术语。",
  ],
  checklist: [
    "先从 `references/components-index.md` 选择最接近的 reference，再实现页面。",
    "新项目接线优先看 `references/app-wiring.md`；导航、分页、弹层分别看 `references/navigationstack.md`、`references/tabview.md`、`references/sheets.md`。",
    "新界面是否把状态留在最近的拥有者，而不是先造 view model。",
    "所有交互面是否有明确加载态、错误态和 dismiss / back 归属。",
    "视图文件顺序是否统一为：环境依赖 → `let` → `@State` → 非视图计算属性 → `init` → `body` → 子视图 / helper。",
    "大型 `body` 是否拆成可命名的子区域，而不是继续堆条件分支。",
    "是否移除了不必要的可选 view model、`bootstrapIfNeeded` 和重复包装。",
    "根视图是否正确持有 `@Observable`，下游只接收必要输入。",
    "交叉引用：并发边界问题看 `swift-concurrency-expert`；性能与重渲染看 `swiftui-performance-audit`；平台设计规范看 `ios-hig-design` / `macos-design-guidelines`。",
  ],
  antiPatterns: [
    defineAntiPattern({
      fail: "sheet(isPresented:) + if let 解包",
      pass: "sheet(item:) 绑定数据",
    }),
    defineAntiPattern({
      fail: "小页面也造 view model",
      pass: "状态就近持有",
    }),
  ],
  invocation: InvocationPolicy.ImplicitAndExplicit,
  platforms: [Platform.Claude, Platform.Codex],
  body: new URL("./SKILL.body.md", import.meta.url),
  tools: [],
  references: [
    defineReference({
      id: "app-wiring",
      source: new URL("./references/app-wiring.md", import.meta.url),
      target: "references/app-wiring.md",
      title: "app-wiring.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "components-index",
      source: new URL("./references/components-index.md", import.meta.url),
      target: "references/components-index.md",
      title: "components-index.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "controls",
      source: new URL("./references/controls.md", import.meta.url),
      target: "references/controls.md",
      title: "controls.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "deeplinks",
      source: new URL("./references/deeplinks.md", import.meta.url),
      target: "references/deeplinks.md",
      title: "deeplinks.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "focus",
      source: new URL("./references/focus.md", import.meta.url),
      target: "references/focus.md",
      title: "focus.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "form",
      source: new URL("./references/form.md", import.meta.url),
      target: "references/form.md",
      title: "form.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "grids",
      source: new URL("./references/grids.md", import.meta.url),
      target: "references/grids.md",
      title: "grids.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "haptics",
      source: new URL("./references/haptics.md", import.meta.url),
      target: "references/haptics.md",
      title: "haptics.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "input-toolbar",
      source: new URL("./references/input-toolbar.md", import.meta.url),
      target: "references/input-toolbar.md",
      title: "input-toolbar.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "lightweight-clients",
      source: new URL("./references/lightweight-clients.md", import.meta.url),
      target: "references/lightweight-clients.md",
      title: "lightweight-clients.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "list",
      source: new URL("./references/list.md", import.meta.url),
      target: "references/list.md",
      title: "list.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "loading-placeholders",
      source: new URL("./references/loading-placeholders.md", import.meta.url),
      target: "references/loading-placeholders.md",
      title: "loading-placeholders.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "macos-settings",
      source: new URL("./references/macos-settings.md", import.meta.url),
      target: "references/macos-settings.md",
      title: "macos-settings.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "matched-transitions",
      source: new URL("./references/matched-transitions.md", import.meta.url),
      target: "references/matched-transitions.md",
      title: "matched-transitions.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "media",
      source: new URL("./references/media.md", import.meta.url),
      target: "references/media.md",
      title: "media.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "menu-bar",
      source: new URL("./references/menu-bar.md", import.meta.url),
      target: "references/menu-bar.md",
      title: "menu-bar.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "mv-patterns",
      source: new URL("./references/mv-patterns.md", import.meta.url),
      target: "references/mv-patterns.md",
      title: "mv-patterns.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "navigationstack",
      source: new URL("./references/navigationstack.md", import.meta.url),
      target: "references/navigationstack.md",
      title: "navigationstack.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "overlay",
      source: new URL("./references/overlay.md", import.meta.url),
      target: "references/overlay.md",
      title: "overlay.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "scrollview",
      source: new URL("./references/scrollview.md", import.meta.url),
      target: "references/scrollview.md",
      title: "scrollview.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "searchable",
      source: new URL("./references/searchable.md", import.meta.url),
      target: "references/searchable.md",
      title: "searchable.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "sheets",
      source: new URL("./references/sheets.md", import.meta.url),
      target: "references/sheets.md",
      title: "sheets.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "split-views",
      source: new URL("./references/split-views.md", import.meta.url),
      target: "references/split-views.md",
      title: "split-views.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "tabview",
      source: new URL("./references/tabview.md", import.meta.url),
      target: "references/tabview.md",
      title: "tabview.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "theming",
      source: new URL("./references/theming.md", import.meta.url),
      target: "references/theming.md",
      title: "theming.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "title-menus",
      source: new URL("./references/title-menus.md", import.meta.url),
      target: "references/title-menus.md",
      title: "title-menus.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "top-bar",
      source: new URL("./references/top-bar.md", import.meta.url),
      target: "references/top-bar.md",
      title: "top-bar.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
    defineReference({
      id: "view-refactoring",
      source: new URL("./references/view-refactoring.md", import.meta.url),
      target: "references/view-refactoring.md",
      title: "view-refactoring.md",
      summary: "Reference material for swiftui-ui-patterns.",
      loadWhen: "Read when the skill body points to this reference or the task needs the detailed material.",
    }),
  ],
});
